In [2]:
import numpy as np

# task: 1

1. Создайте массив длины 10, заполненный нулями
2. Сделайте полученный массив неизменяемым

In [2]:
arr = np.zeros(10)

In [3]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
arr.setflags(write=False)

In [7]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

# task: 2

1. Создайте массив, содержащий 5 равноотстоящих точек, покрывающих диапазон от 0 до 2*pi
2. Создайте массив, содержащий 5 равноотстоящих в логарифмическом масштабе точек, покрывающих диапазон от 10 до 100
3. Составьте из полученных массивов координатную сеть (meshgrid)

In [22]:
arr_x = np.linspace(0, 2*np.pi, 5)

In [24]:
arr_y = np.logspace(10, 100, 5)

In [30]:
np.meshgrid(arr_x, arr_y)

[array([[0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531]]),
 array([[1.00000000e+010, 1.00000000e+010, 1.00000000e+010,
         1.00000000e+010, 1.00000000e+010],
        [3.16227766e+032, 3.16227766e+032, 3.16227766e+032,
         3.16227766e+032, 3.16227766e+032],
        [1.00000000e+055, 1.00000000e+055, 1.00000000e+055,
         1.00000000e+055, 1.00000000e+055],
        [3.16227766e+077, 3.16227766e+077, 3.16227766e+077,
         3.16227766e+077, 3.16227766e+077],
        [1.00000000e+100, 1.00000000e+100, 1.00000000e+100,
         1.00000000e+100, 1.00000000e+100]])]

# task: 3

Создайте двумерный массив 5х5 с элементами 1, 2, 3 и 4 под главной диагональю, остальные элементы заполните нулями

In [15]:
size = 100

In [28]:
%%timeit
arr1 = np.diag(range(1,size), -1)

17.6 µs ± 864 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [17]:
%%timeit
arr2 = np.zeros((size, size))
arr2[range(1,size), range(0,size-1)] = range(1,size)

34.3 µs ± 101 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# task: 4 

1. Создайте функцию-генератор, последовательно возвращающую целые числа от 0 до 9
2. Создайте массив из построенного генератора

In [95]:
def gen_num(min_num, max_num):
    num = min_num
    while num <= max_num:
        yield num
        num += 1   

In [99]:
stop_num = 10000

In [100]:
%%timeit
gen = gen_num(0, stop_num)
np.fromiter(gen, int)

782 µs ± 6.75 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [97]:
def gen_num_range(min_num, max_num):
    for num in range(min_num, max_num+1):
        yield num

In [101]:
%%timeit
gen = gen_num_range(0, stop_num)
np.fromiter(gen, int)

573 µs ± 7.08 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# task: 9

1. Создайте масив из четырех элементов: 0, 10, 20, 30
2. Создайте двухмерный массив 4x5, в котором первый столбец - массив с шага 1, а каждый элемент каждой строки, начиная со второго,  больше предыдущего элемента этой же строки на 1.

In [20]:
last_elem = 4*10

a = np.arange(0, last_elem, 10)
b = np.arange(0,5)

In [21]:
b+a[:, np.newaxis]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [22]:
%%timeit
b+a[:, np.newaxis]

1.18 µs ± 6.73 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [23]:
b+a.reshape(-1,1)

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [24]:
%%timeit
b+a.reshape(-1,1)

1.13 µs ± 6.12 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# task: 11

Создайте двумерный массив 8х8, заполненный 0 и 1 в шахматном порядке

In [53]:
a = np.zeros((8, 8))

In [54]:
a[0:9:2, 0:9:2] = 1

In [56]:
a[1:9:2, 1:9:2] = 1

In [57]:
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# task: 12

1. Создайте одномерный массив целых чисел от 1 до 5
2. Вставьте 0 между каждой парой соседних элементов

In [61]:
a = np.arange(1,6)

In [62]:
idx = np.arange(1,5)

In [63]:
np.insert(a,idx,0)

array([1, 0, 2, 0, 3, 0, 4, 0, 5])

# task: 13

In [ ]:
"Что будет выведено на экран?
x = np.arange(36).reshape(2,3,2,3)
print(x[...,0,...])"
# ellipsis

# 14 - ask
"""
"Что будет выведено на экран?
x = np.arange(16).reshape(4,4)
y = x[:,[2,3]]
y[:] = 0
print(x)
y = x[:,:2]
y[:] = 0
print(x)"
"""

# task: 15

Замените отрицательные элементы массива нулем.

In [85]:
a = np.random.rand(3,4) - 0.5

In [86]:
a

array([[-0.47888139,  0.48476913,  0.43831702,  0.43743761],
       [ 0.40139943,  0.21145055, -0.44597953, -0.4610348 ],
       [-0.34840973, -0.43795691, -0.04163439, -0.18834605]])

In [87]:
a[a < 0] = 0

In [88]:
a

array([[0.        , 0.48476913, 0.43831702, 0.43743761],
       [0.40139943, 0.21145055, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

# task: 16

На примере целочисленного массива x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int) составьте новый массив, не содержащий строки, полностью заполненные одним уникальным значением.

In [3]:
x = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 1], [2, 2, 2]], dtype=int)

In [82]:
x[np.any(x > np.min(x, axis = 1).reshape(-1,1), axis = 1)]

array([[1, 2, 3],
       [2, 2, 1]])

In [ ]:
# min max comp

In [4]:
x[np.max(x, axis = 1) > np.min(x, axis = 1)]

array([[1, 2, 3],
       [2, 2, 1]])

# task: 17

Для заданного одномерного массива x выведите все элементы, не превышающие своих соседей (первый и последний элемент сравниваются только со вторым и предпоследним соответственно).

In [84]:
x = np.random.randint(0, 10, 10)

In [85]:
x

array([9, 1, 3, 8, 8, 2, 6, 7, 4, 3])

In [88]:
x[np.r_[x[:-1]<=x[1:], True] & np.r_[True, x[1:]<=x[:-1]]]

array([1, 2, 3])

# task: 18

1. Создайте двумерный массив 3x3, заполненный случайными числами от 0 до 9
2. Отсортируйте строки массива по возрастанию значения во втором столбце

In [1]:
import numpy as np

In [19]:
a = np.random.randint(0, 10, (3, 3))

In [20]:
a

array([[5, 2, 3],
       [0, 9, 8],
       [4, 0, 2]])

In [21]:
a[np.argsort(a[:, 1])]

array([[4, 0, 2],
       [5, 2, 3],
       [0, 9, 8]])

# task 19
Поменяйте местами первую и вторую строки двумерного массива

In [140]:
a = np.random.randint(0, 20, (5, 3))

In [141]:
a

array([[ 0,  2, 16],
       [ 7,  6,  8],
       [15,  5, 16],
       [ 1, 10, 12],
       [10,  2,  6]])

In [142]:
np.vstack((a[1], a[0], a[2:]))

array([[ 7,  6,  8],
       [ 0,  2, 16],
       [15,  5, 16],
       [ 1, 10, 12],
       [10,  2,  6]])

In [ ]:
# подумать

In [149]:
# NEW:
a[[1, 0]] = a[[0, 1]]

In [150]:
a

array([[ 7,  6,  8],
       [ 0,  2, 16],
       [15,  5, 16],
       [ 1, 10, 12],
       [10,  2,  6]])

# task 20

1. Создайте массив 3x5, заполненный числами от 0 до 14
2. Выберите 1, 3 строки и 2, 4 столбцы, не удаляя элементы из массива

In [152]:
a = np.random.randint(0, 15, (3, 5))

In [153]:
a

array([[ 6,  7,  8,  1,  6],
       [13,  7, 12, 13,  2],
       [ 5,  3,  6, 10,  8]])

In [154]:
a[np.ix_([0, 2], [1, 3])]

array([[ 7,  1],
       [ 3, 10]])

In [155]:
# array slicing + способы slicing

In [162]:
a[[0, 2]][:, [1, 3]]

array([[ 7,  1],
       [ 3, 10]])

# task 21
Что будет выведено на экран?

```Python
x = np.arange(5)
x[[0,0,1]] = range(3)
print(x)
x[[1,2,1]] += 1
print(x)
```

my ans:
```
[1, 2, 2, 3, 4]
[1, 3, 3, 3, 4]
```

In [48]:
x = np.arange(5)
x[[0, 0, 1]] = range(3)
print(x)
x[[1, 2, 1]] += 1
print(x)

[1 2 2 3 4]
[1 3 3 3 4]


# task: 22
Перечислите все известные вам способы преобразования заданного n-мерного массива в одномерный. Какой из способов работает быстрее и почему?

In [53]:
shape_param = 100

x = np.random.randint(0, 10, [shape_param]*4)

In [55]:
%%time
np.ravel(x).shape

CPU times: user 15 µs, sys: 22 µs, total: 37 µs
Wall time: 47.4 µs


(100000000,)

In [56]:
%%time
np.reshape(x, (-1,)).shape

CPU times: user 36 µs, sys: 0 ns, total: 36 µs
Wall time: 43.2 µs


(100000000,)

In [59]:
%%time
x.flatten().shape

CPU times: user 145 ms, sys: 177 ms, total: 322 ms
Wall time: 321 ms


(100000000,)

In [ ]:
# что под капотом

# task: 23
1. Создайте массив, заполненный случайными значениями
2. Замените максимальные значения массива средним

In [62]:
a = np.random.randint(0, 9, 10)

In [63]:
a

array([4, 5, 7, 0, 7, 7, 3, 4, 5, 1])

In [64]:
a[a == np.max(a)] = np.mean(a)

In [65]:
a

array([4, 5, 4, 0, 4, 4, 3, 4, 5, 1])

# task: 24
1. Создайте двумерный массив 6x6, заполненный случайными значениями
2. Сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом

In [67]:
a = np.random.randint(0, 10, (6, 6))

In [68]:
a

array([[2, 1, 9, 8, 0, 2],
       [8, 2, 7, 3, 5, 2],
       [6, 7, 9, 4, 4, 8],
       [6, 5, 2, 5, 5, 1],
       [5, 8, 5, 1, 8, 5],
       [5, 7, 3, 1, 1, 4]])

In [69]:
np.min(a, axis=0)

array([2, 1, 2, 1, 0, 1])

In [70]:
np.sum(a, axis=1)/np.min(a, axis=0)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([11., 27., 19., 24., inf, 21.])

# task: 25

1. Создайте одномерный массив длины 10, заполненный случайными значениями
2. Линейно отобразите элементы массива в отрезок [0, 1], при этом минимальный элемент должен отобразиться в 0, а максимальный - в 1

In [71]:
x = np.random.randint(0, 9, (10,))

In [73]:
x

array([7, 5, 3, 3, 1, 2, 7, 5, 7, 3])

In [76]:
(x-np.min(x))/(np.max(x)-np.min(x))

array([1.        , 0.66666667, 0.33333333, 0.33333333, 0.        ,
       0.16666667, 1.        , 0.66666667, 1.        , 0.33333333])

# task: 26
Замените все вхождения nan в двумерный массив средним значением по соответствующему столбцу

In [89]:
x = np.random.random((3, 5))

In [92]:
x[0, :] = np.nan

In [103]:
x

array([[       nan,        nan,        nan,        nan,        nan],
       [0.90200379, 0.97395237, 0.05983503, 0.10892731, 0.43362284],
       [0.15501955, 0.53910296, 0.83876406, 0.91402764, 0.66574833]])

In [109]:
x[np.isnan(x)] = np.nanmean(x, axis=0)

In [110]:
x

array([[0.52851167, 0.75652767, 0.44929955, 0.51147747, 0.54968559],
       [0.90200379, 0.97395237, 0.05983503, 0.10892731, 0.43362284],
       [0.15501955, 0.53910296, 0.83876406, 0.91402764, 0.66574833]])

# task 27: 
Проверьте, есть ли в двумерном массиве столбец, полностью заполненый нулями.

In [113]:
x = np.random.randint(0, 2, (3, 5))

In [114]:
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0],
       [0, 0, 1, 1, 1]])

In [117]:
np.any(np.count_nonzero(x, axis = 1) == 0)

False

# task 28:
1. Создайте массив случайных чисел от 0 до 9 размером 3x4x3x4
2. Вычислите суммы элементов по двум последним осям

In [123]:
a = np.random.randint(0, 10, (3, 4, 3, 4))

In [124]:
np.sum(a, axis=(2, 3))

array([[67, 59, 58, 70],
       [60, 73, 58, 57],
       [51, 50, 63, 30]])