In [1]:
import numpy as np

# task: 1

1. Создайте массив длины 10, заполненный нулями
2. Сделайте полученный массив неизменяемым

In [2]:
arr = np.zeros(10)

In [3]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
arr.setflags(write=False)

In [5]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

# task: 2

1. Создайте массив, содержащий 5 равноотстоящих точек, покрывающих диапазон от 0 до 2*pi
2. Создайте массив, содержащий 5 равноотстоящих в логарифмическом масштабе точек, покрывающих диапазон от 10 до 100
3. Составьте из полученных массивов координатную сеть (meshgrid)

In [6]:
arr_x = np.linspace(0, 2*np.pi, 5)

In [7]:
arr_y = np.logspace(10, 100, 5)

In [8]:
np.meshgrid(arr_x, arr_y)

[array([[0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531]]),
 array([[1.00000000e+010, 1.00000000e+010, 1.00000000e+010,
         1.00000000e+010, 1.00000000e+010],
        [3.16227766e+032, 3.16227766e+032, 3.16227766e+032,
         3.16227766e+032, 3.16227766e+032],
        [1.00000000e+055, 1.00000000e+055, 1.00000000e+055,
         1.00000000e+055, 1.00000000e+055],
        [3.16227766e+077, 3.16227766e+077, 3.16227766e+077,
         3.16227766e+077, 3.16227766e+077],
        [1.00000000e+100, 1.00000000e+100, 1.00000000e+100,
         1.00000000e+100, 1.00000000e+100]])]

# task: 3

Создайте двумерный массив 5х5 с элементами 1, 2, 3 и 4 под главной диагональю, остальные элементы заполните нулями

In [9]:
size = 100

In [10]:
%%timeit
arr1 = np.diag(range(1,size), -1)

18.7 µs ± 1.7 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [11]:
%%timeit
arr2 = np.zeros((size, size))
arr2[range(1,size), range(0,size-1)] = range(1,size)

39.8 µs ± 154 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# task: 4 

1. Создайте функцию-генератор, последовательно возвращающую целые числа от 0 до 9
2. Создайте массив из построенного генератора

In [12]:
def gen_num(min_num, max_num):
    num = min_num
    while num <= max_num:
        yield num
        num += 1   

In [13]:
stop_num = 10000

In [14]:
%%timeit
gen = gen_num(0, stop_num)
np.fromiter(gen, int)

869 µs ± 21.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [15]:
def gen_num_range(min_num, max_num):
    for num in range(min_num, max_num+1):
        yield num

In [16]:
%%timeit
gen = gen_num_range(0, stop_num)
np.fromiter(gen, int)

619 µs ± 10.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# task: 9

1. Создайте масив из четырех элементов: 0, 10, 20, 30
2. Создайте двухмерный массив 4x5, в котором первый столбец - массив с шага 1, а каждый элемент каждой строки, начиная со второго,  больше предыдущего элемента этой же строки на 1.

In [17]:
last_elem = 4*10

a = np.arange(0, last_elem, 10)
b = np.arange(0,5)

In [18]:
b+a[:, np.newaxis]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [19]:
%%timeit
b+a[:, np.newaxis]

1.19 µs ± 37.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [20]:
b+a.reshape(-1,1)

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [21]:
%%timeit
b+a.reshape(-1,1)

1.17 µs ± 29.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# task: 11

Создайте двумерный массив 8х8, заполненный 0 и 1 в шахматном порядке

In [22]:
a = np.zeros((8, 8))

In [23]:
a[0:9:2, 0:9:2] = 1

In [24]:
a[1:9:2, 1:9:2] = 1

In [25]:
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# task: 12

1. Создайте одномерный массив целых чисел от 1 до 5
2. Вставьте 0 между каждой парой соседних элементов

In [26]:
length = 5

a = np.arange(1, length+1)

In [27]:
%%timeit
np.insert(a, np.arange(1, length), 0)

12.5 µs ± 80.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
%%timeit
np.insert(a, slice(1, length), 0)

13 µs ± 599 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [29]:
%%timeit
b = np.zeros(length*2-1)
b[0::2] = a

1.03 µs ± 25.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# task: 13

"Что будет выведено на экран?
x = np.arange(36).reshape(2,3,2,3)
print(x[...,0,...])"
# ellipsis

# 14
"""
"Что будет выведено на экран?
x = np.arange(16).reshape(4,4)
y = x[:,[2,3]]
y[:] = 0
print(x)
y = x[:,:2]
y[:] = 0
print(x)"
"""

# task: 15

Замените отрицательные элементы массива нулем.

In [30]:
a = np.random.rand(3,4) - 0.5

In [31]:
a

array([[ 0.11156467,  0.47367323,  0.059751  , -0.40797663],
       [-0.44142637,  0.32666401,  0.31531377,  0.13730759],
       [-0.162918  ,  0.19467065, -0.21405937, -0.41597822]])

In [32]:
a[a < 0] = 0

In [33]:
a

array([[0.11156467, 0.47367323, 0.059751  , 0.        ],
       [0.        , 0.32666401, 0.31531377, 0.13730759],
       [0.        , 0.19467065, 0.        , 0.        ]])

# task: 16

На примере целочисленного массива x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int) составьте новый массив, не содержащий строки, полностью заполненные одним уникальным значением.

In [34]:
x = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 1], [2, 2, 2]], dtype=int)

In [35]:
x[np.any(x > np.min(x, axis = 1).reshape(-1,1), axis = 1)]

array([[1, 2, 3],
       [2, 2, 1]])

In [36]:
# min max comp

In [37]:
x[np.max(x, axis = 1) > np.min(x, axis = 1)]

array([[1, 2, 3],
       [2, 2, 1]])

# task: 17

Для заданного одномерного массива x выведите все элементы, не превышающие своих соседей (первый и последний элемент сравниваются только со вторым и предпоследним соответственно).

In [38]:
x = np.random.randint(0, 10, 10)

In [39]:
x

array([8, 9, 9, 2, 3, 3, 3, 3, 8, 5])

In [40]:
x[np.r_[x[:-1]<=x[1:], True] & np.r_[True, x[1:]<=x[:-1]]]

array([8, 2, 3, 3, 3, 5])

# task: 18

1. Создайте двумерный массив 3x3, заполненный случайными числами от 0 до 9
2. Отсортируйте строки массива по возрастанию значения во втором столбце

In [41]:
a = np.random.randint(0, 10, (3, 3))

In [42]:
a

array([[0, 0, 5],
       [2, 3, 7],
       [2, 9, 7]])

In [43]:
a[np.argsort(a[:, 1])]

array([[0, 0, 5],
       [2, 3, 7],
       [2, 9, 7]])

# task 19
Поменяйте местами первую и вторую строки двумерного массива

In [44]:
shape = (100, 100)

a = np.random.randint(0, 20, shape)

In [45]:
b = a.copy()

In [46]:
%%timeit
np.vstack((a[1], a[0], a[2:]))

8.44 µs ± 328 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [47]:
%%timeit
a[[1, 0]] = a[[0, 1]]

4.43 µs ± 12.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [48]:
%%timeit
b[1::-1] = b[0:2]

941 ns ± 20 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# task 20

1. Создайте массив 3x5, заполненный числами от 0 до 14
2. Выберите 1, 3 строки и 2, 4 столбцы, не удаляя элементы из массива

In [49]:
a = np.random.randint(0, 15, (3, 5))

In [50]:
a

array([[13,  6,  2,  0,  6],
       [ 1,  6, 13,  2,  5],
       [ 6,  1,  9,  1,  0]])

In [51]:
a[np.ix_([0, 2], [1, 3])]

array([[6, 0],
       [1, 1]])

In [52]:
# array slicing + способы slicing

In [53]:
a[[0, 2]][:, [1, 3]]

array([[6, 0],
       [1, 1]])

# task 21
Что будет выведено на экран?

```Python
x = np.arange(5)
x[[0,0,1]] = range(3)
print(x)
x[[1,2,1]] += 1
print(x)
```

my ans:
```
[1, 2, 2, 3, 4]
[1, 3, 3, 3, 4]
```

In [54]:
x = np.arange(5)
x[[0, 0, 1]] = range(3)
print(x)
x[[1, 2, 1]] += 1
print(x)

[1 2 2 3 4]
[1 3 3 3 4]


# task: 22
Перечислите все известные вам способы преобразования заданного n-мерного массива в одномерный. Какой из способов работает быстрее и почему?

In [55]:
shape_param = 100

x = np.random.randint(0, 10, [shape_param]*4)

In [56]:
%%time
np.ravel(x).shape

CPU times: user 25 µs, sys: 2 µs, total: 27 µs
Wall time: 29.8 µs


(100000000,)

In [57]:
%%time
np.reshape(x, (-1,)).shape

CPU times: user 30 µs, sys: 2 µs, total: 32 µs
Wall time: 35 µs


(100000000,)

In [58]:
%%time
x.flatten().shape

CPU times: user 127 ms, sys: 148 ms, total: 275 ms
Wall time: 274 ms


(100000000,)

In [59]:
# что под капотом

# task: 23
1. Создайте массив, заполненный случайными значениями
2. Замените максимальные значения массива средним

In [60]:
a = np.random.randint(0, 9, 1000)

In [61]:
a

array([5, 4, 4, 2, 1, 6, 5, 4, 0, 0, 6, 7, 2, 6, 2, 2, 6, 2, 3, 1, 8, 2,
       1, 5, 8, 2, 2, 0, 5, 8, 7, 0, 0, 6, 7, 4, 8, 3, 4, 6, 8, 0, 2, 6,
       7, 2, 2, 7, 2, 1, 5, 7, 1, 5, 8, 0, 4, 8, 2, 6, 2, 3, 2, 0, 6, 8,
       5, 1, 7, 3, 0, 3, 0, 0, 0, 1, 2, 4, 1, 6, 2, 0, 8, 7, 1, 4, 5, 6,
       0, 1, 7, 1, 1, 7, 8, 2, 7, 0, 8, 8, 1, 8, 8, 7, 7, 5, 8, 2, 0, 6,
       7, 6, 0, 3, 8, 2, 2, 7, 6, 3, 4, 5, 6, 3, 1, 6, 2, 5, 2, 8, 2, 0,
       8, 1, 2, 3, 2, 4, 8, 6, 5, 1, 1, 6, 3, 1, 1, 6, 6, 2, 0, 7, 6, 6,
       2, 5, 6, 0, 0, 2, 2, 1, 2, 3, 5, 5, 0, 6, 3, 5, 8, 6, 0, 4, 2, 7,
       0, 6, 8, 8, 1, 7, 5, 3, 8, 0, 2, 8, 1, 8, 1, 0, 6, 3, 2, 6, 3, 4,
       8, 3, 3, 3, 8, 2, 6, 3, 1, 7, 7, 2, 8, 0, 6, 4, 0, 1, 1, 0, 0, 8,
       5, 8, 8, 0, 3, 5, 2, 8, 3, 5, 5, 5, 6, 5, 4, 1, 6, 6, 4, 4, 1, 0,
       2, 6, 2, 2, 0, 7, 7, 8, 7, 5, 1, 4, 1, 1, 7, 8, 8, 8, 3, 1, 1, 5,
       4, 2, 0, 7, 7, 6, 5, 4, 2, 7, 8, 1, 7, 0, 1, 1, 5, 6, 0, 3, 8, 5,
       8, 5, 6, 4, 5, 8, 5, 4, 5, 3, 1, 1, 0, 1, 4,

In [62]:
b = a.copy()
c = a.copy()
d = a.copy()

In [63]:
%%timeit
np.place(a, a==np.max(a), np.mean(a))

17.3 µs ± 429 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [64]:
%%timeit
b[b == np.max(b)] = np.mean(b)

15.6 µs ± 619 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [65]:
%%timeit
np.put(c, np.max(c), np.mean(c))

14.7 µs ± 387 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [66]:
# argmax

In [67]:
%%timeit
d[np.argmax(d)] = np.mean(d)

9.93 µs ± 29.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [68]:
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

# task: 24
1. Создайте двумерный массив 6x6, заполненный случайными значениями
2. Сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом

In [69]:
a = np.random.randint(0, 10, (6, 6))

In [70]:
a

array([[7, 6, 3, 2, 6, 1],
       [1, 0, 4, 6, 9, 4],
       [1, 0, 3, 5, 1, 1],
       [8, 2, 5, 8, 2, 6],
       [5, 6, 4, 9, 1, 1],
       [8, 4, 5, 3, 4, 5]])

In [71]:
np.min(a, axis=0)

array([1, 0, 3, 2, 1, 1])

In [72]:
np.sum(a, axis=1)/np.min(a, axis=0)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([25.        ,         inf,  3.66666667, 15.5       , 26.        ,
       29.        ])

# task: 25

1. Создайте одномерный массив длины 10, заполненный случайными значениями
2. Линейно отобразите элементы массива в отрезок [0, 1], при этом минимальный элемент должен отобразиться в 0, а максимальный - в 1

In [73]:
x = np.random.randint(0, 9, (10,))

In [74]:
x

array([2, 8, 6, 2, 3, 8, 0, 0, 5, 1])

In [75]:
(x-np.min(x))/np.ptp(x)

array([0.25 , 1.   , 0.75 , 0.25 , 0.375, 1.   , 0.   , 0.   , 0.625,
       0.125])

# task: 26
Замените все вхождения nan в двумерный массив средним значением по соответствующему столбцу

In [76]:
x = np.random.random((3, 5))

In [77]:
x[0, :] = np.nan

In [78]:
x

array([[       nan,        nan,        nan,        nan,        nan],
       [0.64250651, 0.40458162, 0.16183652, 0.74594631, 0.73069351],
       [0.92394365, 0.54258557, 0.10022834, 0.66990157, 0.08745915]])

In [79]:
x[np.isnan(x)] = np.nanmean(x, axis=0)

In [80]:
x

array([[0.78322508, 0.4735836 , 0.13103243, 0.70792394, 0.40907633],
       [0.64250651, 0.40458162, 0.16183652, 0.74594631, 0.73069351],
       [0.92394365, 0.54258557, 0.10022834, 0.66990157, 0.08745915]])

In [81]:
x.fill(np.nan)

In [ ]:
#x[np.isnan(x)] = np.nanmean(x, axis=0)

In [83]:
np.nan_to_num(x, nan = np.nanmean(x, axis=0))

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: Mean of empty slice
  """Entry point for launching an IPython kernel.


array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

In [84]:
x

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

# task 27: 
Проверьте, есть ли в двумерном массиве столбец, полностью заполненый нулями.

In [85]:
x = np.random.randint(-100, 100, (1000, 1000))

In [86]:
x

array([[ 56,  55, -91, ..., -26,  89,  44],
       [ 30, -95,  41, ..., -96,  -2,  32],
       [-70, -45,   7, ...,   9,  78, -38],
       ...,
       [ 93,  84, -89, ...,  79,  40,  36],
       [ 25,  57, -37, ..., -90,  39,  46],
       [-87, -84,  -1, ...,  22, -39,  43]])

In [87]:
%%timeit
np.any(np.count_nonzero(x, axis = 1) == 0)

1.28 ms ± 42.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [88]:
%%timeit
np.any(np.all(x == 0, axis = 0))

419 µs ± 740 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [89]:
%%timeit
np.any(np.prod(x + 1, axis = 0) == 1)

1.04 ms ± 13.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# task 28:
1. Создайте массив случайных чисел от 0 до 9 размером 3x4x3x4
2. Вычислите суммы элементов по двум последним осям

In [90]:
a = np.random.randint(0, 10, (3, 4, 3, 4))

In [91]:
np.sum(a, axis=(2, 3))

array([[49, 49, 68, 60],
       [46, 60, 43, 54],
       [57, 57, 45, 43]])

# task 29:

1. Любым способом создайте два массива одинаковой длины
2. Создайте массив, в котором на четных позициях будут стоять элементы с соответствующих позиций первого массива, а на нечетных - с соответствующих позиций второго

In [92]:
length = 10
a = np.ones(length)
b = np.ones(length) + 1

In [93]:
c = np.zeros(length * 2)
c[0::2] = a
c[1::2] = b

# task 30:

На примере массива ```x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])``` вычислите долю пропущенных значений

In [94]:
x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])

In [95]:
x.size

8

In [96]:
np.sum(np.isnan(x))/np.prod(x.shape)

0.375

# task 31:
На примере массива ```x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])``` составьте массив из уникальных значений массива без учета nan

In [97]:
scale = 100

x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]]*scale)

In [98]:
%%timeit
uni = np.unique(x)
uni[~ np.isnan(uni)]

14 µs ± 444 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [99]:
%%timeit
nonan = x[~ np.isnan(x)]
nonan = np.unique(nonan)

13.1 µs ± 352 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# task 32:

На примере массива ```x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])``` найдите максимальный элемент в массиве среди элементов, перед которыми стоит нулевой

In [100]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

In [101]:
np.max(x[np.r_[False, x == 0][:-1]])

5

# task 33:
Пусть заданы два массива одинакового размера. Поэлементно разделите один массив на другой. В случае, если делитель равен нулю, соответствующему элементу результирующего массива присвойте нуль.

In [102]:
length = 1000
a = np.random.randint(1, 10, length)
b = np.random.randint(0, 3, length)

In [103]:
%%timeit
c = np.divide(a, b, where=(b!=0))
c[b == 0] = 0

9.91 µs ± 140 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [104]:
%%timeit
c = np.divide(a, b)
c[b == 0] = 0

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


7.07 µs ± 254 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [105]:
%%timeit
c = np.where(b == 0, 0, a / b)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


7.3 µs ± 223 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# task 34:

Пусть заданы два массива ```x = np.ones(10)``` и ```i = np.array([0, 1, 2, 3, 5, 5, 5, 8])```. Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [106]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])

In [107]:
pos, counts = np.unique(i, return_counts=True)

In [108]:
x[pos] += counts

In [109]:
x

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

# task 35:

По заданному массиву ```y = np.bincount([0, 0, 3, 8, 10, 10, 11])``` постройте массив x такой, чтобы ```np.bincount(x) = y```

In [110]:
y = np.bincount([0, 0, 3, 8, 10, 10, 11])

In [111]:
x = np.repeat(np.arange(0, y.shape[0]), y)

In [112]:
np.all(np.bincount(x) == y)

True

# task 36:

Определите самые часто встречающиеся элементы в массиве целых неотрицательных чисел.
Решите задачу на примере массива ```x = np.array([0,1,2,0,6,6,7,4,5,4])```.

In [113]:
x = np.array([0,1,2,0,6,6,7,4,5,4])

In [114]:
val, freq = np.unique(x, return_counts=True)

In [115]:
val[freq==np.max(freq)]

array([0, 4, 6])

# task 37:

Разбейте двумерный массив на список двумерных массивов по уникальным значениям в первом столбце.
Решите задачу на примере массива ```x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5]])```, в результате должен получиться список ```[array([[1, 2], [1, 3]]), array([[2, 2]]), array([[3, 4], [3, 5]])]```.

In [116]:
x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5]])

In [117]:
x

array([[1, 2],
       [1, 3],
       [2, 2],
       [3, 4],
       [3, 5]])

In [118]:
[np.array([[1, 2], [1, 3]]), np.array([[2, 2]]), np.array([[3, 4], [3, 5]])]

[array([[1, 2],
        [1, 3]]),
 array([[2, 2]]),
 array([[3, 4],
        [3, 5]])]

In [119]:
_, freq = np.unique(x[:, :1], return_counts=True)

In [120]:
np.array_split(x, np.cumsum(freq)[:-1], axis=0)

[array([[1, 2],
        [1, 3]]),
 array([[2, 2]]),
 array([[3, 4],
        [3, 5]])]

# task 38:

По заданному одномерному массиву неотрицательных чисел постройте список подмассивов, сожержащих элементы из полуинтервалов ```[i * 10, (i+1) * 10), i = 0, 1, 2, …```
Решите задачу на примере массива ```x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20])```, в результате должен получиться список ```[array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])]```.

In [121]:
x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20])

In [122]:
[np.array([0, 2, 2, 8]), np.array([10, 11, 13, 18]), np.array([20, 24]), np.array([34])]

[array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])]

In [123]:
np.array_split(np.sort(x), np.cumsum(np.histogram(x, bins = np.arange(0, np.max(x), 10))[0]))

[array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])]