In [2]:
import numpy as np

# task: 1

1. Создайте массив длины 10, заполненный нулями
2. Сделайте полученный массив неизменяемым

In [2]:
arr = np.zeros(10)

In [3]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
arr.setflags(write=False)

In [7]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

# task: 2

1. Создайте массив, содержащий 5 равноотстоящих точек, покрывающих диапазон от 0 до 2*pi
2. Создайте массив, содержащий 5 равноотстоящих в логарифмическом масштабе точек, покрывающих диапазон от 10 до 100
3. Составьте из полученных массивов координатную сеть (meshgrid)

In [22]:
arr_x = np.linspace(0, 2*np.pi, 5)

In [24]:
arr_y = np.logspace(10, 100, 5)

In [30]:
np.meshgrid(arr_x, arr_y)

[array([[0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531]]),
 array([[1.00000000e+010, 1.00000000e+010, 1.00000000e+010,
         1.00000000e+010, 1.00000000e+010],
        [3.16227766e+032, 3.16227766e+032, 3.16227766e+032,
         3.16227766e+032, 3.16227766e+032],
        [1.00000000e+055, 1.00000000e+055, 1.00000000e+055,
         1.00000000e+055, 1.00000000e+055],
        [3.16227766e+077, 3.16227766e+077, 3.16227766e+077,
         3.16227766e+077, 3.16227766e+077],
        [1.00000000e+100, 1.00000000e+100, 1.00000000e+100,
         1.00000000e+100, 1.00000000e+100]])]

# task: 3

Создайте двумерный массив 5х5 с элементами 1, 2, 3 и 4 под главной диагональю, остальные элементы заполните нулями

In [15]:
size = 100

In [28]:
%%timeit
arr1 = np.diag(range(1,size), -1)

17.6 µs ± 864 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [17]:
%%timeit
arr2 = np.zeros((size, size))
arr2[range(1,size), range(0,size-1)] = range(1,size)

34.3 µs ± 101 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# task: 4 

1. Создайте функцию-генератор, последовательно возвращающую целые числа от 0 до 9
2. Создайте массив из построенного генератора

In [95]:
def gen_num(min_num, max_num):
    num = min_num
    while num <= max_num:
        yield num
        num += 1   

In [99]:
stop_num = 10000

In [100]:
%%timeit
gen = gen_num(0, stop_num)
np.fromiter(gen, int)

782 µs ± 6.75 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [97]:
def gen_num_range(min_num, max_num):
    for num in range(min_num, max_num+1):
        yield num

In [101]:
%%timeit
gen = gen_num_range(0, stop_num)
np.fromiter(gen, int)

573 µs ± 7.08 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# task: 9

1. Создайте масив из четырех элементов: 0, 10, 20, 30
2. Создайте двухмерный массив 4x5, в котором первый столбец - массив с шага 1, а каждый элемент каждой строки, начиная со второго,  больше предыдущего элемента этой же строки на 1.

In [20]:
last_elem = 4*10

a = np.arange(0, last_elem, 10)
b = np.arange(0,5)

In [21]:
b+a[:, np.newaxis]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [22]:
%%timeit
b+a[:, np.newaxis]

1.18 µs ± 6.73 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [23]:
b+a.reshape(-1,1)

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [24]:
%%timeit
b+a.reshape(-1,1)

1.13 µs ± 6.12 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# task: 11

Создайте двумерный массив 8х8, заполненный 0 и 1 в шахматном порядке

In [53]:
a = np.zeros((8, 8))

In [54]:
a[0:9:2, 0:9:2] += 1

In [56]:
a[1:9:2, 1:9:2] += 1

In [57]:
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# task: 12

1. Создайте одномерный массив целых чисел от 1 до 5
2. Вставьте 0 между каждой парой соседних элементов

In [61]:
a = np.arange(1,6)

In [62]:
idx = np.arange(1,5)

In [63]:
np.insert(a,idx,0)

array([1, 0, 2, 0, 3, 0, 4, 0, 5])

# task: 13

In [ ]:
"Что будет выведено на экран?
x = np.arange(36).reshape(2,3,2,3)
print(x[...,0,...])"
# ellipsis

# 14 - ask
"""
"Что будет выведено на экран?
x = np.arange(16).reshape(4,4)
y = x[:,[2,3]]
y[:] = 0
print(x)
y = x[:,:2]
y[:] = 0
print(x)"
"""

# task: 15

Замените отрицательные элементы массива нулем.

In [85]:
a = np.random.rand(3,4) - 0.5

In [86]:
a

array([[-0.47888139,  0.48476913,  0.43831702,  0.43743761],
       [ 0.40139943,  0.21145055, -0.44597953, -0.4610348 ],
       [-0.34840973, -0.43795691, -0.04163439, -0.18834605]])

In [87]:
a[a < 0] = 0

In [88]:
a

array([[0.        , 0.48476913, 0.43831702, 0.43743761],
       [0.40139943, 0.21145055, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

# task: 16

На примере целочисленного массива x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int) составьте новый массив, не содержащий строки, полностью заполненные одним уникальным значением.

In [74]:
x = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 1], [2, 2, 2]], dtype=int)

In [82]:
x[np.any(x > np.min(x, axis = 1).reshape(-1,1), axis = 1)]

array([[1, 2, 3],
       [2, 2, 1]])

# task: 17

Для заданного одномерного массива x выведите все элементы, не превышающие своих соседей (первый и последний элемент сравниваются только со вторым и предпоследним соответственно).

In [84]:
x = np.random.randint(0, 10, 10)

In [85]:
x

array([9, 1, 3, 8, 8, 2, 6, 7, 4, 3])

In [88]:
x[np.r_[x[:-1]<=x[1:], True] & np.r_[True, x[1:]<=x[:-1]]]

array([1, 2, 3])