Task from article [Advanced NumPy: Master stride tricks with 25 illustrated exercises](https://towardsdatascience.com/advanced-numpy-master-stride-tricks-with-25-illustrated-exercises-923a9393ab20)

In [1]:
import math
import numpy as np
from numpy.lib.stride_tricks import as_strided

# 1D exercises

## Task 1: 
Slice first 3 elements.

In: matrix 5*5 with numbers from 1 to 25 

Out: row 1*3 [1, 2, 3]


In [2]:
in_matrix = np.arange(1, 26).reshape((5, 5))
slice_num = 3
as_strided(in_matrix, shape=(slice_num,))

array([1, 2, 3])

## Task 2:
Slice first 8 elements.

In: matrix 5*5 with numbers from 1 to 25 

Out: row 1*8  [1, 2, 3, ..., 8]

In [3]:
slice_num = 8
as_strided(in_matrix, shape=(slice_num,))

array([1, 2, 3, 4, 5, 6, 7, 8])

## Task 3:
Flatten a 2d array

In: matrix 5*5  [1, 2, 3] with numbers from 1 to 25 

Out: row 1*25  [1, 2, 3, ..., 25]

In [4]:
as_strided(in_matrix, shape=(in_matrix.size,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

## Task 4:
Skip every other element

In: matrix 5*5  [1, 2, 3]  with numbers from 1 to 25 

Out: row 1*3 ([1, 3, 5])

In [5]:
it_size = in_matrix.itemsize
skip = 2
as_strided(in_matrix, shape=(3, ), strides=(skip*it_size, ))

array([1, 3, 5])

## Task 5:
Slice first column

In: matrix 5*5  with numbers from 1 to 25 

Out: row 1*4 [1, 6, 11, 16]

In [6]:
col_slice = 4
as_strided(in_matrix, shape=(col_slice, ), strides=(in_matrix.shape[1]*it_size, ))

array([ 1,  6, 11, 16])

## Task 6:
Slice a diagonal

In: matrix 5*5  with numbers from 1 to 25 

Out: row 1*5 [1, 7, 13, 19, 25]

In [7]:
out_shape = (min(in_matrix.shape), ) # (5, )
out_strides = ((in_matrix.shape[1]+1)*it_size, ) # (6*8, )
as_strided(in_matrix, shape=out_shape, strides=out_strides)

array([ 1,  7, 13, 19, 25])

## Task 7:
Repeat the frist element

In: matrix 5*5  with numbers from 1 to 25 

Out: row 1*5 [1, 1, 1, 1, 1]

In [8]:
repeat_times = 5
as_strided(in_matrix, shape=(repeat_times, ), strides=(0, ))

array([1, 1, 1, 1, 1])

# 2D exercises

## Task 8:
Simple 2D slicing

In: matrix 5*5  with numbers from 1 to 25 

Out: matrix 3*4 with cols from 0 to 3 and rows from 0 to 2

In [9]:
slicing_rows = (0, 4)
slicing_cols = (0, 5)
out_shape = (slicing_rows[1]-slicing_rows[0]-1, slicing_cols[1]-slicing_cols[0]-1) # (3, 4)
out_strides = in_matrix.strides # (5*8, 1*8)
as_strided(in_matrix, shape=out_shape, strides=out_strides)

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

## Task 9:
Slice a zigzag

In: matrix 5*5  with numbers from 1 to 25 

Out: matrix 4*2 [[1, 2], [7, 8], [13, 14], [19, 20]]

In [10]:
zigzag_len = 2
out_shape = (in_matrix.shape[0]-zigzag_len+1, zigzag_len) # shape=(4, 2)
out_strides = ((in_matrix.shape[1]+1)*it_size, 1*it_size) # (6*8, 1*8)
as_strided(in_matrix, shape=out_shape, strides=out_strides)

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]])

## Task 10:
Sparse slicing

In: matrix 5*5  with numbers from 1 to 25 

Out: matrix 3*3 with dilation 2

In [11]:
dilation = 2
out_shape = [math.ceil(shape_elem/dilation) for shape_elem in in_matrix.shape] # (3, 3)
out_strides = [stride_elem*dilation for stride_elem in in_matrix.strides] # (2*5*8, 2*1*8)
as_strided(in_matrix, shape=out_shape, strides=out_strides)

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

## Task 11:
Transpose a 2D array

In: matrix 5*5  with numbers from 1 to 25 

Out: matrix 3*3 of cols from 0 to 2 rows from 0 to 2 and transposed

In [12]:
out_shape = (3, 3) 
out_strides = (1*it_size, in_matrix.shape[1]*it_size) # (1*8, 5*8)
as_strided(in_matrix, shape=out_shape, strides=out_strides)

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13]])

## Task 12:
Repeat the first column 4 times

In: matrix 5*5  with numbers from 1 to 25 

Out: matrix 5*4

In [13]:
repeat_times = 4
out_shape = (in_matrix.shape[0], repeat_times) # (5, 4)
out_strides = (in_matrix.shape[1]*it_size, 0) # (5*8, 0)
as_strided(in_matrix, shape=out_shape, strides=out_strides)

array([[ 1,  1,  1,  1],
       [ 6,  6,  6,  6],
       [11, 11, 11, 11],
       [16, 16, 16, 16],
       [21, 21, 21, 21]])

## Task 13:
Reshape 1D array to 2D array

In: row 1*12 with values from 1 to 12

Out: matrix 4*3

In [14]:
in_row = np.arange(1, 13)

In [15]:
output_shape = (4, 3)
output_strides = (output_shape[1]*it_size, 1*it_size) # (3*8, 1*8)
as_strided(in_row, shape=output_shape, strides=output_strides)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Task 14:
Slide a 1D window

In: row 1*10 with values from 1 to 10

Out: matrix 8*3
    
 * first col: from 1 to 8
 * second col: from 2 to 9
 * third col: from 3 to 10

In [16]:
in_row = np.arange(1, 11)

In [17]:
window_shape = 8
output_shape = (window_shape, len(in_row)-window_shape+1) # (8, 3)
as_strided(in_row, shape=output_shape, strides=(1*it_size, 1*it_size))

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10]])

## Task 15:
Slide a 2D window then flatten

<img src="images/strides/15_task.PNG" height=800, width=800>


In [18]:
first_col = np.arange(0, 60, 10).reshape(6, 1)
in_matrix = np.hstack([first_col, first_col+1])

In [19]:
in_matrix

array([[ 0,  1],
       [10, 11],
       [20, 21],
       [30, 31],
       [40, 41],
       [50, 51]])

In [20]:
window_shape = (3, 2)
out_matrix_shape = (in_matrix.shape[0]-window_shape[0]+1, np.prod(window_shape)) # (4, 6)
out_matrix_strides = (window_shape[1]*it_size, 1*it_size) # (2*8, 1*8)
as_strided(in_matrix, shape=out_matrix_shape, strides=out_matrix_strides)

array([[ 0,  1, 10, 11, 20, 21],
       [10, 11, 20, 21, 30, 31],
       [20, 21, 30, 31, 40, 41],
       [30, 31, 40, 41, 50, 51]])

## Task 16:
Collapse an axis from a 3D array

<img src="images/strides/16_task.PNG" height=600, width=600>


In [21]:
first_part = np.arange(1, 5).reshape(2, 2)
elements_amount = 3
in_array = np.array([first_part + num*4 for num in range(elements_amount)])

In [22]:
in_array

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [23]:
out_matrix_shape = (in_array.shape[0], in_array.shape[1]*in_array.shape[2]) # (3, 4)
out_matrix_strides = (in_array.shape[1]*in_array.shape[2]*it_size, 1*it_size) # (4*8, 1*8)
as_strided(in_array, shape=out_matrix_shape, strides=out_matrix_strides)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 3D exercises