In [1]:
import numpy as np

# task: 1

1. Создайте массив длины 10, заполненный нулями
2. Сделайте полученный массив неизменяемым

In [2]:
arr = np.zeros(10)

In [3]:
arr.setflags(write=False)

In [4]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

# task: 2

1. Создайте массив, содержащий 5 равноотстоящих точек, покрывающих диапазон от 0 до 2*pi
2. Создайте массив, содержащий 5 равноотстоящих в логарифмическом масштабе точек, покрывающих диапазон от 10 до 100
3. Составьте из полученных массивов координатную сеть (meshgrid)

In [5]:
arr_x = np.linspace(0, 2*np.pi, 5)

In [6]:
arr_y = np.logspace(10, 100, 5)

In [7]:
np.meshgrid(arr_x, arr_y)

[array([[0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531]]),
 array([[1.00000000e+010, 1.00000000e+010, 1.00000000e+010,
         1.00000000e+010, 1.00000000e+010],
        [3.16227766e+032, 3.16227766e+032, 3.16227766e+032,
         3.16227766e+032, 3.16227766e+032],
        [1.00000000e+055, 1.00000000e+055, 1.00000000e+055,
         1.00000000e+055, 1.00000000e+055],
        [3.16227766e+077, 3.16227766e+077, 3.16227766e+077,
         3.16227766e+077, 3.16227766e+077],
        [1.00000000e+100, 1.00000000e+100, 1.00000000e+100,
         1.00000000e+100, 1.00000000e+100]])]

# task: 3

Создайте двумерный массив 5х5 с элементами 1, 2, 3 и 4 под главной диагональю, остальные элементы заполните нулями

In [8]:
size = 100

In [9]:
%%timeit
arr1 = np.diag(range(1, size), -1)

18.5 µs ± 775 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
%%timeit
arr2 = np.zeros((size, size))
arr2[range(1,size), range(0,size-1)] = range(1,size)

41.2 µs ± 838 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### Ответ:

In [11]:
np.diag(range(1, 5), -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# task: 4 

1. Создайте функцию-генератор, последовательно возвращающую целые числа от 0 до 9
2. Создайте массив из построенного генератора

In [12]:
def gen_num(min_num, max_num):
    num = min_num
    while num <= max_num:
        yield num
        num += 1   

In [13]:
stop_num = 10000

In [14]:
%%timeit
gen = gen_num(0, stop_num)
np.fromiter(gen, int)

835 µs ± 311 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [15]:
def gen_num_range(min_num, max_num):
    for num in range(min_num, max_num+1):
        yield num

In [16]:
%%timeit
gen = gen_num_range(0, stop_num)
np.fromiter(gen, int)

561 µs ± 312 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Ответ

In [17]:
def gen_num_range(min_num, max_num):
    for num in range(min_num, max_num+1):
        yield num
        
gen = gen_num_range(0, 9)
np.fromiter(gen, int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# task: 9

1. Создайте масив из четырех элементов: 0, 10, 20, 30
2. Создайте двухмерный массив 4x5, в котором первый столбец - массив с шага 1, а каждый элемент каждой строки, начиная со второго,  больше предыдущего элемента этой же строки на 1.

In [18]:
last_elem = 4*1000

a = np.arange(0, last_elem, 10)
b = np.arange(0,5)

In [19]:
%%timeit
b+a[:, np.newaxis]

5.01 µs ± 84.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
%%timeit
b+a.reshape(-1,1)

5.24 µs ± 49.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Ответ:

In [21]:
last_elem = 4*10
a = np.arange(0, last_elem, 10)
b = np.arange(0,5)
print(b+a.reshape(-1,1))

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]


# task: 11

Создайте двумерный массив 8х8, заполненный 0 и 1 в шахматном порядке

In [22]:
a = np.zeros((8, 8))

In [23]:
a[0:9:2, 0:9:2] = 1

In [24]:
a[1:9:2, 1:9:2] = 1

In [25]:
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# task: 12

1. Создайте одномерный массив целых чисел от 1 до 5
2. Вставьте 0 между каждой парой соседних элементов

In [26]:
length = 5

a = np.arange(1, length+1)

In [27]:
%%timeit
np.insert(a, np.arange(1, length), 0)

12.1 µs ± 304 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
%%timeit
np.insert(a, slice(1, length), 0)

12.5 µs ± 305 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [29]:
%%timeit
b = np.zeros(length*2-1)
b[0::2] = a

947 ns ± 4.58 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Ответ:

In [30]:
length = 5
a = np.arange(1, length+1)
b = np.zeros(length*2-1)
b[0::2] = a
print(b)

[1. 0. 2. 0. 3. 0. 4. 0. 5.]


# task: 13

"Что будет выведено на экран?
x = np.arange(36).reshape(2,3,2,3)
print(x[...,0,...])"
ellipsis

14
"""
"Что будет выведено на экран?
x = np.arange(16).reshape(4,4)
y = x[:,[2,3]]
y[:] = 0
print(x)
y = x[:,:2]
y[:] = 0
print(x)"
"""

# task: 15

Замените отрицательные элементы массива нулем.

In [31]:
a = np.random.rand(3, 4) - 0.5

In [32]:
a

array([[ 0.02579324,  0.3669078 ,  0.03068941, -0.49955624],
       [-0.48405753, -0.22978654,  0.1937285 ,  0.20310052],
       [ 0.08162181,  0.37707253, -0.03898233, -0.15518242]])

In [33]:
a[a < 0] = 0

In [34]:
a

array([[0.02579324, 0.3669078 , 0.03068941, 0.        ],
       [0.        , 0.        , 0.1937285 , 0.20310052],
       [0.08162181, 0.37707253, 0.        , 0.        ]])

# task: 16

На примере целочисленного массива ```x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int)``` составьте новый массив, не содержащий строки, полностью заполненные одним уникальным значением.

In [35]:
x = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 1], [2, 2, 2]], dtype=int)

In [36]:
x[np.max(x, axis = 1) > np.min(x, axis = 1)]

array([[1, 2, 3],
       [2, 2, 1]])

# task: 17

Для заданного одномерного массива x выведите все элементы, не превышающие своих соседей (первый и последний элемент сравниваются только со вторым и предпоследним соответственно).

In [37]:
x = np.random.randint(0, 10, 10)

In [38]:
x

array([6, 9, 5, 6, 1, 0, 2, 7, 4, 9])

In [39]:
x[np.r_[x[:-1]<=x[1:], True] & np.r_[True, x[1:]<=x[:-1]]]

array([6, 5, 0, 4])

# task: 18

1. Создайте двумерный массив 3x3, заполненный случайными числами от 0 до 9
2. Отсортируйте строки массива по возрастанию значения во втором столбце

In [40]:
a = np.random.randint(0, 10, (3, 3))

In [41]:
a

array([[6, 5, 8],
       [7, 5, 9],
       [9, 4, 3]])

In [42]:
a[np.argsort(a[:, 1])]

array([[9, 4, 3],
       [6, 5, 8],
       [7, 5, 9]])

# task 19
Поменяйте местами первую и вторую строки двумерного массива

In [43]:
shape = (100, 100)

a = np.random.randint(0, 20, shape)

In [44]:
b = a.copy()

In [45]:
%%timeit
np.vstack((a[1], a[0], a[2:]))

7.92 µs ± 77.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [46]:
%%timeit
a[[1, 0]] = a[[0, 1]]

4.3 µs ± 16.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [47]:
%%timeit
b[1::-1] = b[0:2]

920 ns ± 3.79 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Ответ:

In [48]:
shape = (3, 4)

a = np.random.randint(0, 20, shape)
print("In:\n", a)
a[1::-1] = a[0:2]
print("Out:\n", a)

In:
 [[ 6 16 18  3]
 [ 6  8  2 10]
 [ 2 19 16 16]]
Out:
 [[ 6  8  2 10]
 [ 6 16 18  3]
 [ 2 19 16 16]]


# task 20

1. Создайте массив 3x5, заполненный числами от 0 до 14
2. Выберите 1, 3 строки и 2, 4 столбцы, не удаляя элементы из массива

In [49]:
shape = (30, 150)
a = np.random.randint(0, 15, shape)

In [50]:
%%timeit
a[np.ix_([0, 2], [1, 3])]

10.9 µs ± 736 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [51]:
%%timeit
a[[0, 2]][:, [1, 3]]

4.48 µs ± 9.88 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Ответ:

In [52]:
shape = (3, 5)
a = np.random.randint(0, 15, shape)
print("In:\n", a)
print("Out:\n", a[[0, 2]][:, [1, 3]])

In:
 [[13  6  2  8  0]
 [ 6  2 13  2 12]
 [13  8  2  7 12]]
Out:
 [[6 8]
 [8 7]]


# task 21
Что будет выведено на экран?

```Python
x = np.arange(5)
x[[0,0,1]] = range(3)
print(x)
x[[1,2,1]] += 1
print(x)
```

**My ans:**
```
[1, 2, 2, 3, 4]
[1, 3, 3, 3, 4]
```

In [53]:
x = np.arange(5)
x[[0, 0, 1]] = range(3)
print(x)
x[[1, 2, 1]] += 1
print(x)

[1 2 2 3 4]
[1 3 3 3 4]


# task: 22
Перечислите все известные вам способы преобразования заданного n-мерного массива в одномерный. Какой из способов работает быстрее и почему?

In [54]:
shape_param = 100

x = np.random.randint(0, 10, [shape_param]*4)

In [55]:
%%time
np.ravel(x).shape

CPU times: user 29 µs, sys: 2 µs, total: 31 µs
Wall time: 35.3 µs


(100000000,)

In [56]:
%%time
np.reshape(x, (-1,)).shape

CPU times: user 22 µs, sys: 2 µs, total: 24 µs
Wall time: 28.4 µs


(100000000,)

In [57]:
%%time
x.flatten().shape

CPU times: user 142 ms, sys: 133 ms, total: 274 ms
Wall time: 274 ms


(100000000,)

### Ответ:

reshape и ravel работают с view, в то время как flatten создает копию. ravel - частный случай reshape.

# task: 23
1. Создайте массив, заполненный случайными значениями
2. Замените максимальные значения массива средним

In [58]:
a = np.random.randint(0, 9, 1000)

In [59]:
b = a.copy()
c = a.copy()
d = a.copy()

In [60]:
%%timeit
np.place(a, a==np.max(a), np.mean(a))

17.1 µs ± 37.4 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [61]:
%%timeit
b[b == np.max(b)] = np.mean(b)

15.2 µs ± 460 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [62]:
%%timeit
np.put(c, np.max(c), np.mean(c))

13.8 µs ± 71 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [63]:
%%timeit
d[np.argmax(d)] = np.mean(d)
# возвращает только одно значение индекса, а не все

9.83 µs ± 28.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Ответ:

In [64]:
a = np.random.randint(0, 9, 10).astype(float)
print("In:\n", a)
print(f"Mean: {np.mean(a)}, Max: {np.max(a)}")
a[a == np.max(a)] = np.mean(a)
print("Out:\n", a)

In:
 [6. 7. 5. 4. 1. 1. 6. 5. 0. 8.]
Mean: 4.3, Max: 8.0
Out:
 [6.  7.  5.  4.  1.  1.  6.  5.  0.  4.3]


# task: 24
1. Создайте двумерный массив 6x6, заполненный случайными значениями
2. Сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом

In [65]:
a = np.random.randint(0, 10, (6, 6))

In [66]:
a

array([[5, 2, 5, 7, 9, 5],
       [2, 8, 0, 5, 7, 2],
       [7, 0, 1, 2, 8, 8],
       [3, 0, 1, 7, 2, 2],
       [0, 3, 1, 4, 3, 9],
       [5, 6, 1, 2, 6, 5]])

In [67]:
np.min(a, axis=0)

array([0, 0, 0, 2, 2, 2])

In [68]:
np.sum(a, axis=1)/np.min(a, axis=0)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ inf,  inf,  inf,  7.5, 10. , 12.5])

# task: 25

1. Создайте одномерный массив длины 10, заполненный случайными значениями
2. Линейно отобразите элементы массива в отрезок [0, 1], при этом минимальный элемент должен отобразиться в 0, а максимальный - в 1

In [69]:
x = np.random.randint(0, 9, (10,))

In [70]:
x

array([2, 0, 1, 3, 0, 7, 4, 1, 2, 5])

In [71]:
(x-np.min(x))/np.ptp(x)

array([0.28571429, 0.        , 0.14285714, 0.42857143, 0.        ,
       1.        , 0.57142857, 0.14285714, 0.28571429, 0.71428571])

# task: 26
Замените все вхождения nan в двумерный массив средним значением по соответствующему столбцу

In [72]:
x = np.random.random((3, 5))

In [73]:
x[0, :] = np.nan

In [74]:
x

array([[       nan,        nan,        nan,        nan,        nan],
       [0.28835723, 0.34865754, 0.86005437, 0.72939575, 0.44520374],
       [0.46279927, 0.21990792, 0.66458295, 0.26538218, 0.73241981]])

In [75]:
x[np.isnan(x)] = np.nanmean(x, axis=0)

In [76]:
x

array([[0.37557825, 0.28428273, 0.76231866, 0.49738897, 0.58881177],
       [0.28835723, 0.34865754, 0.86005437, 0.72939575, 0.44520374],
       [0.46279927, 0.21990792, 0.66458295, 0.26538218, 0.73241981]])

In [77]:
x[:, 0] = np.nan

In [78]:
x

array([[       nan, 0.28428273, 0.76231866, 0.49738897, 0.58881177],
       [       nan, 0.34865754, 0.86005437, 0.72939575, 0.44520374],
       [       nan, 0.21990792, 0.66458295, 0.26538218, 0.73241981]])

In [79]:
#x[np.isnan(x)] = np.nanmean(x, axis=0)

In [80]:
np.nan_to_num(x, nan = np.nanmean(x, axis=0))

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: Mean of empty slice
  """Entry point for launching an IPython kernel.


array([[       nan, 0.28428273, 0.76231866, 0.49738897, 0.58881177],
       [       nan, 0.34865754, 0.86005437, 0.72939575, 0.44520374],
       [       nan, 0.21990792, 0.66458295, 0.26538218, 0.73241981]])

In [81]:
x

array([[       nan, 0.28428273, 0.76231866, 0.49738897, 0.58881177],
       [       nan, 0.34865754, 0.86005437, 0.72939575, 0.44520374],
       [       nan, 0.21990792, 0.66458295, 0.26538218, 0.73241981]])

# task 27: 
Проверьте, есть ли в двумерном массиве столбец, полностью заполненый нулями.

In [82]:
x = np.random.randint(-100, 100, (1000, 1000))

In [83]:
x

array([[ 52, -25, -41, ...,   4, -70,   7],
       [ 60,  87,  65, ...,  55, -22,  35],
       [-21,  16, -70, ...,  -3,  29, -12],
       ...,
       [ 96,  55,   1, ..., -12,  28, -69],
       [  4,  50,  27, ...,  34, -67, -95],
       [ 49,  91,  19, ..., -16, -28,  86]])

In [84]:
%%timeit
np.any(np.count_nonzero(x, axis = 1) == 0)

1.22 ms ± 2.19 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [85]:
%%timeit
np.any(np.all(x == 0, axis = 0))

402 µs ± 290 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [86]:
%%timeit
np.any(np.prod(x + 1, axis = 0) == 1)

1 ms ± 749 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Ответ:

In [87]:
x = np.random.randint(-1, 1, (3, 10))
print(x)
print(np.any(np.all(x == 0, axis = 0)))

[[-1 -1  0 -1  0 -1  0  0  0 -1]
 [-1  0  0  0 -1  0  0  0 -1  0]
 [-1 -1  0 -1  0 -1  0 -1  0  0]]
True


# task 28:
1. Создайте массив случайных чисел от 0 до 9 размером 3x4x3x4
2. Вычислите суммы элементов по двум последним осям

In [88]:
a = np.random.randint(0, 10, (3, 4, 3, 4))

In [89]:
np.sum(a, axis=(2, 3))

array([[44, 64, 63, 58],
       [54, 48, 60, 52],
       [54, 47, 56, 62]])

# task 29:

1. Любым способом создайте два массива одинаковой длины
2. Создайте массив, в котором на четных позициях будут стоять элементы с соответствующих позиций первого массива, а на нечетных - с соответствующих позиций второго

In [90]:
length = 10
a = np.ones(length)
b = np.ones(length) + 1
print(a, "\n", b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [91]:
c = np.zeros(length * 2)
c[0::2] = a
c[1::2] = b
print(c)

[1. 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 2.]


# task 30:

На примере массива ```x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])``` вычислите долю пропущенных значений

In [92]:
x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])

In [93]:
np.sum(np.isnan(x))/x.size

0.375

# task 31:
На примере массива ```x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])``` составьте массив из уникальных значений массива без учета nan

In [94]:
scale = 100

x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]]*scale)

In [95]:
%%timeit
uni = np.unique(x)
uni[~ np.isnan(uni)]

13.4 µs ± 43.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [96]:
%%timeit
nonan = x[~ np.isnan(x)]
nonan = np.unique(nonan)

12.3 µs ± 49.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Ответ:

In [97]:
x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
print("In:\n", x)
uni = np.unique(x)
uni = uni[~np.isnan(uni)]
print("Out:\n", uni)

In:
 [[ 1.  2.]
 [nan  3.]
 [ 5.  5.]
 [nan nan]]
Out:
 [1. 2. 3. 5.]


# task 32:

На примере массива ```x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])``` найдите максимальный элемент в массиве среди элементов, перед которыми стоит нулевой

In [98]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

In [99]:
np.max(x[np.r_[False, x == 0][:-1]])

5

# task 33:
Пусть заданы два массива одинакового размера. Поэлементно разделите один массив на другой. В случае, если делитель равен нулю, соответствующему элементу результирующего массива присвойте нуль.

In [100]:
length = 1000
a = np.random.randint(1, 10, length)
b = np.random.randint(0, 3, length)

In [101]:
%%timeit
c = np.divide(a, b, where=(b!=0))
c[b == 0] = 0

9.66 µs ± 23.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [102]:
%%timeit
c = np.divide(a, b)
c[b == 0] = 0

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


6.83 µs ± 38.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [103]:
%%timeit
c = np.where(b == 0, 0, a / b)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


7.18 µs ± 17.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Ответ:

In [104]:
length = 10
a = np.random.randint(1, 10, length)
b = np.random.randint(0, 3, length)
c = np.divide(a, b)
c[b == 0] = 0
print("In:\n", a, "\n", b)
print("Out:", c)

In:
 [3 2 4 4 2 8 5 4 4 1] 
 [0 2 2 1 2 1 2 2 2 0]
Out: [0.  1.  2.  4.  1.  8.  2.5 2.  2.  0. ]


/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


# task 34:

Пусть заданы два массива ```x = np.ones(10)``` и ```i = np.array([0, 1, 2, 3, 5, 5, 5, 8])```. Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [105]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])

In [106]:
pos, counts = np.unique(i, return_counts=True)

In [107]:
x[pos] += counts

In [108]:
x

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

# task 35:

По заданному массиву ```y = np.bincount([0, 0, 3, 8, 10, 10, 11])``` постройте массив x такой, чтобы ```np.bincount(x) = y```

In [109]:
y = np.bincount([0, 0, 3, 8, 10, 10, 11])

In [110]:
x = np.repeat(np.arange(0, y.shape[0]), y)

In [111]:
np.all(np.bincount(x) == y)

True

# task 36:

Определите самые часто встречающиеся элементы в массиве целых неотрицательных чисел.
Решите задачу на примере массива ```x = np.array([0,1,2,0,6,6,7,4,5,4])```.

In [112]:
x = np.array([0,1,2,0,6,6,7,4,5,4])

In [113]:
val, freq = np.unique(x, return_counts=True)

In [114]:
val[freq==np.max(freq)]

array([0, 4, 6])

# task 37:

Разбейте двумерный массив на список двумерных массивов по уникальным значениям в первом столбце.
Решите задачу на примере массива ```x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5]])```, в результате должен получиться список ```[array([[1, 2], [1, 3]]), array([[2, 2]]), array([[3, 4], [3, 5]])]```.

In [115]:
x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5]])

In [116]:
x

array([[1, 2],
       [1, 3],
       [2, 2],
       [3, 4],
       [3, 5]])

In [117]:
[np.array([[1, 2], [1, 3]]), np.array([[2, 2]]), np.array([[3, 4], [3, 5]])]

[array([[1, 2],
        [1, 3]]),
 array([[2, 2]]),
 array([[3, 4],
        [3, 5]])]

In [118]:
_, freq = np.unique(x[:, :1], return_counts=True)

In [119]:
np.array_split(x, np.cumsum(freq)[:-1], axis=0)

[array([[1, 2],
        [1, 3]]),
 array([[2, 2]]),
 array([[3, 4],
        [3, 5]])]

# task 38:

По заданному одномерному массиву неотрицательных чисел постройте список подмассивов, сожержащих элементы из полуинтервалов ```[i * 10, (i+1) * 10), i = 0, 1, 2, …```
Решите задачу на примере массива ```x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20])```, в результате должен получиться список ```[array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])]```.

In [120]:
x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20])

In [121]:
[np.array([0, 2, 2, 8]), np.array([10, 11, 13, 18]), np.array([20, 24]), np.array([34])]

[array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])]

In [122]:
np.array_split(np.sort(x), np.cumsum(np.histogram(x, bins = np.arange(0, np.max(x), 10))[0]))

[array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])]

# task 39:

Перечислите все известные вам способы соединения заданных двумерных массивов по вертикали. Какой из способов работает быстрее?

In [123]:
shape = (10000, 10000)
a = np.random.randint(1, 5, shape)
b = np.random.randint(5, 10, shape)

In [124]:
%%time
x = np.vstack((a,b))

CPU times: user 263 ms, sys: 285 ms, total: 548 ms
Wall time: 547 ms


In [125]:
print(x.shape)

(20000, 10000)


In [126]:
%%time
x = np.concatenate((a,b))

CPU times: user 284 ms, sys: 269 ms, total: 553 ms
Wall time: 552 ms


In [127]:
print(x.shape)

(20000, 10000)


### Ответ:

In [128]:
shape = (2, 10)
a = np.random.randint(1, 5, shape)
b = np.random.randint(5, 10, shape)
x = np.concatenate((a,b))
print("In:\n", a, "\nand:\n", b)
print("Out:\n", x)

In:
 [[4 2 1 4 3 4 2 3 1 3]
 [3 1 4 3 1 1 3 1 3 4]] 
and:
 [[6 5 9 9 9 5 9 7 8 6]
 [5 7 7 8 9 5 7 8 8 9]]
Out:
 [[4 2 1 4 3 4 2 3 1 3]
 [3 1 4 3 1 1 3 1 3 4]
 [6 5 9 9 9 5 9 7 8 6]
 [5 7 7 8 9 5 7 8 8 9]]


# task 40:

Для двух одномерных массивов ```x = np.arange(3)``` и ```y = np.arange(5)``` постройте двумерный массив строки которого - всевозможные пары элементов из x и y.

In [129]:
x = np.arange(3)
y = np.arange(5)

In [130]:
a, b = np.meshgrid(x, y)

In [131]:
np.reshape(np.stack((a, b), axis=-1), (-1, 2))

array([[0, 0],
       [1, 0],
       [2, 0],
       [0, 1],
       [1, 1],
       [2, 1],
       [0, 2],
       [1, 2],
       [2, 2],
       [0, 3],
       [1, 3],
       [2, 3],
       [0, 4],
       [1, 4],
       [2, 4]])

# task 41:

По двум входным одномерным массивам одинаковой длины составьте массив пар элементов с одинаковыми индесами.
Решите задачу на примере массивов ```x = np.array([1,2,3,4])``` и ```y = np.array([5,6,7,8])```.

In [132]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [133]:
np.stack((x, y), axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# task 42:
По заданному непустому списку двумерных массивов одинаковых размеров составьте трехмерный массив в котором вдоль нулевой оси расположены массивы из списка, между каждой парой которых вставлен массив полностью заполненный нулями.
Решите задачу для списка ```l = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]), np.array([[9, 10], [11, 12]])]```.

In [134]:
l = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]), np.array([[9, 10], [11, 12]])]

In [135]:
l

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

# ?

# task 43:
Преобразуйте одномерный массив ```x = np.array([3,7,2,5,0,9,8,2,4,5])``` в двумерный массив, первая строка которого - элементы массива x с индексами от 0 до 4, вторая строка - с 1 до 5 и т.д.

In [136]:
x = np.array([3,7,2,5,0,9,8,2,4,5])

In [137]:
x.reshape(-1, 5)

array([[3, 7, 2, 5, 0],
       [9, 8, 2, 4, 5]])

# task 44:
Для заданного двумерного массива постройте трехмерный массив, содержащий всевозможные неперекрывающиеся блоки размера 3x3, начиная с левого верхнего угла. Если высота/ширина исходного массива не кратна трем, исключите из рассмотрения последние строки/столбцы.
Решите задачу на примере массива ```x = np.arange(49).reshape(7,7)```.

In [138]:
x = np.arange(49).reshape(7,7)

In [139]:
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [140]:
#x = x[:(x.shape[0]//3)*3, :(x.shape[1]//3)*3].copy()

In [141]:
#x

In [142]:
np.lib.stride_tricks.as_strided(x, strides=(3*x.itemsize, 7*x.itemsize, 1*x.itemsize), shape=(2, 3, 3))

array([[[ 0,  1,  2],
        [ 7,  8,  9],
        [14, 15, 16]],

       [[ 3,  4,  5],
        [10, 11, 12],
        [17, 18, 19]]])

In [143]:
np.lib.stride_tricks.as_strided(x[3:], strides=(3*x.itemsize, 7*x.itemsize, 1*x.itemsize), shape=(2, 3, 3))

array([[[21, 22, 23],
        [28, 29, 30],
        [35, 36, 37]],

       [[24, 25, 26],
        [31, 32, 33],
        [38, 39, 40]]])

# ?

# task 45:
Примените маску к элементам одномерного массива, отличающимся от среднего на величину, большую чем 3 стандартных отклонения.
Решите задачу на примере массива из 20 элеметнов, первый из которых равен 100, а остальные равны 0.

In [144]:
length = 1000
a = np.zeros(length)
a[0] = 5*length

In [145]:
mean, std = np.mean(a), np.std(a)
print(mean, std)

5.0 158.03480629279107


In [146]:
%%time
a[np.abs(a-mean) > 3*std]

CPU times: user 167 µs, sys: 7 µs, total: 174 µs
Wall time: 141 µs


array([5000.])

In [147]:
%%time
a[(a > mean + 3 * std) | (a < mean - 3 * std)]

CPU times: user 98 µs, sys: 4 µs, total: 102 µs
Wall time: 128 µs


array([5000.])

### Ответ:

In [148]:
length = 20
a = np.zeros(length)
a[0] = 5*length
mean, std = np.mean(a), np.std(a)
a[np.abs(a-mean) > 3*std]

array([100.])

# task 46:
Удалите из двумерного массива столбцы, ко всем элементам которых применена маска.
Решите задачу на примере массива ```x = np.ma.array([[1, 2, 3], [4, 5, 6]], mask=[[1, 1, 0], [0, 1, 0]])```.

In [149]:
x = np.ma.array([[1, 2, 3], [4, 5, 6]], mask=[[1, 1, 0], [0, 1, 0]])

In [150]:
x

masked_array(
  data=[[--, --, 3],
        [4, --, 6]],
  mask=[[ True,  True, False],
        [False,  True, False]],
  fill_value=999999)

In [151]:
np.delete(x.data, np.prod(x.mask, axis=0).astype(bool), axis=1)

array([[1, 3],
       [4, 6]])

# task 47:
Примените маску к минимальному и максимальному элементу каждой строки двумерного массива.
Решите задачу на примере массива ```x = np.arange(25).reshape(5, 5)```.

In [152]:
x = np.arange(25).reshape(5, 5)

In [153]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [154]:
np.ma.array(x, mask=np.isin(x, (np.max(x, axis=1), np.min(x, axis=1))))

masked_array(
  data=[[--, 1, 2, 3, --],
        [--, 6, 7, 8, --],
        [--, 11, 12, 13, --],
        [--, 16, 17, 18, --],
        [--, 21, 22, 23, --]],
  mask=[[ True, False, False, False,  True],
        [ True, False, False, False,  True],
        [ True, False, False, False,  True],
        [ True, False, False, False,  True],
        [ True, False, False, False,  True]],
  fill_value=999999)

# task 48:

Примените медианный фильтр с нечетной шириной окна k к заданному одномерному массиву a: i-е значение результирующего массива вычисляется как медиана подмассива ```a[i - (k-1)/2: i - (k-1)/2 + 1]```. В случае если границы окна выходят за границы массива, дополните исходный массив требуемым числом элементов a[0] или a[-1] с нужной стороны.
Решите задачу на примере массива ```a = np.array([3, 8, 100, -3, -7, 4, 0, 2])``` и ширины окна k = 5.

In [155]:
a = np.array([3, 8, 100, -3, -7, 4, 0, 2])
k = 5

In [156]:
skip = int((k-1)/2)
a = np.pad(a, skip, mode='edge')
print(a)

[  3   3   3   8 100  -3  -7   4   0   2   2   2]


In [157]:
res = []
for i in range(skip, len(a)-skip):
    res.append(np.median(a[i - int((k-1)/2): i + int((k-1)/2) + 1]))

In [158]:
res

[3.0, 3.0, 3.0, 4.0, 0.0, 0.0, 2.0, 2.0]

# task 49:

По заданному массиву a размера Nx2 постройте одномерный массив длины N, i-й элемент которого - сумма i-го элемента первого столбца массива a и элемента первого столбца, индекс которого содержится в i-й строке второго столбца. В случае, если во втором столбце массива a содержится индекс, выходящий за границы, к элементу первого столбца ничего не прибавляйте.
Решите задачу на примере массива ```a = np.array([[10, 1], [3, 1], [8, 2], [6, 1], [12, 5]])```.

In [159]:
a = np.array([[10, 1], [3, 1], [8, 2], [6, 1], [12, 5]])

In [160]:
a

array([[10,  1],
       [ 3,  1],
       [ 8,  2],
       [ 6,  1],
       [12,  5]])

In [161]:
res = []
for x, y in a:
    res.append(x + a[y, 0] if y<len(a) else x)

In [162]:
res

[13, 6, 16, 9, 12]

# task 50:

По заданному двумерному массиву размера NxN постройте словарь, ключи которого - индексы диагоналей, параллельных побочной (нумерация начинается с 0), а значения - списки элементов исходного массива, лежащих на соответствующих диагоналях.
Решите задачу на примере массива ```a = np.arange(16).reshape(4, 4)```, в результате должен получиться словарь
```
{0: [0],
 1: [1, 4],
 2: [2, 5, 8],
 3: [3, 6, 9, 12],
 4: [7, 10, 13],
 5: [11, 14],
 6: [15]}.
```

In [163]:
a = np.arange(16).reshape(4, 4)

In [164]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [165]:
a[:, ::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [166]:
res = {}
for iterator in range(-a.shape[1]+1, a.shape[1]):
    res[iterator+3] = list(np.diag(a[:, ::-1], -iterator))

In [167]:
res

{0: [0],
 1: [1, 4],
 2: [2, 5, 8],
 3: [3, 6, 9, 12],
 4: [7, 10, 13],
 5: [11, 14],
 6: [15]}