In [1]:
import numpy as np

### tasks: 1-4

In [2]:
arr = np.zeros(10)

In [3]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
arr.setflags(write=False)

In [7]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [22]:
arr_x = np.linspace(0, 2*np.pi,5)

In [24]:
arr_y = np.logspace(10, 100, 5)

In [30]:
np.meshgrid(arr_x, arr_y)#, sparse=True)

[array([[0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531]]),
 array([[1.00000000e+010, 1.00000000e+010, 1.00000000e+010,
         1.00000000e+010, 1.00000000e+010],
        [3.16227766e+032, 3.16227766e+032, 3.16227766e+032,
         3.16227766e+032, 3.16227766e+032],
        [1.00000000e+055, 1.00000000e+055, 1.00000000e+055,
         1.00000000e+055, 1.00000000e+055],
        [3.16227766e+077, 3.16227766e+077, 3.16227766e+077,
         3.16227766e+077, 3.16227766e+077],
        [1.00000000e+100, 1.00000000e+100, 1.00000000e+100,
         1.00000000e+100, 1.00000000e+100]])]

In [32]:
arr_diag = np.zeros((5,5))

In [33]:
arr_diag[range(1,5),range(0,4)]=range(1,5)

In [34]:
arr_diag

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [35]:
gen = range(0,10)
arr_gen = np.array(gen)

In [36]:
arr_gen

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])