In [1]:
import numpy as np

# task: 1

1. Создайте массив длины 10, заполненный нулями
2. Сделайте полученный массив неизменяемым

In [2]:
arr = np.zeros(10)

In [3]:
arr.setflags(write=False)

In [4]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

# task: 2

1. Создайте массив, содержащий 5 равноотстоящих точек, покрывающих диапазон от 0 до 2*pi
2. Создайте массив, содержащий 5 равноотстоящих в логарифмическом масштабе точек, покрывающих диапазон от 10 до 100
3. Составьте из полученных массивов координатную сеть (meshgrid)

In [5]:
arr_x = np.linspace(0, 2*np.pi, 5)

In [6]:
arr_y = np.logspace(10, 100, 5)

In [7]:
np.meshgrid(arr_x, arr_y)

[array([[0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531]]),
 array([[1.00000000e+010, 1.00000000e+010, 1.00000000e+010,
         1.00000000e+010, 1.00000000e+010],
        [3.16227766e+032, 3.16227766e+032, 3.16227766e+032,
         3.16227766e+032, 3.16227766e+032],
        [1.00000000e+055, 1.00000000e+055, 1.00000000e+055,
         1.00000000e+055, 1.00000000e+055],
        [3.16227766e+077, 3.16227766e+077, 3.16227766e+077,
         3.16227766e+077, 3.16227766e+077],
        [1.00000000e+100, 1.00000000e+100, 1.00000000e+100,
         1.00000000e+100, 1.00000000e+100]])]

# task: 3

Создайте двумерный массив 5х5 с элементами 1, 2, 3 и 4 под главной диагональю, остальные элементы заполните нулями

In [8]:
size = 100

In [9]:
%%timeit
arr1 = np.diag(range(1, size), -1)

18.7 µs ± 298 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
%%timeit
arr2 = np.zeros((size, size))
arr2[range(1,size), range(0,size-1)] = range(1,size)

43 µs ± 280 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### Ответ:

In [11]:
np.diag(range(1, 5), -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# task: 4 

1. Создайте функцию-генератор, последовательно возвращающую целые числа от 0 до 9
2. Создайте массив из построенного генератора

In [12]:
def gen_num(min_num, max_num):
    num = min_num
    while num <= max_num:
        yield num
        num += 1   

In [13]:
stop_num = 10000

In [14]:
%%timeit
gen = gen_num(0, stop_num)
np.fromiter(gen, int)

854 µs ± 1.82 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [15]:
def gen_num_range(min_num, max_num):
    for num in range(min_num, max_num+1):
        yield num

In [16]:
%%timeit
gen = gen_num_range(0, stop_num)
np.fromiter(gen, int)

574 µs ± 15.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Ответ:

In [17]:
gen = gen_num_range(0, stop_num)
np.fromiter(gen, int)

array([    0,     1,     2, ...,  9998,  9999, 10000])

# task: 9

1. Создайте масив из четырех элементов: 0, 10, 20, 30
2. Создайте двухмерный массив 4x5, в котором первый столбец - массив с шага 1, а каждый элемент каждой строки, начиная со второго,  больше предыдущего элемента этой же строки на 1.

In [18]:
last_elem = 4*1000

a = np.arange(0, last_elem, 10)
b = np.arange(0,5)

In [19]:
%%timeit
b+a[:, np.newaxis]

5.41 µs ± 91.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
%%timeit
b+a.reshape(-1,1)

5.16 µs ± 111 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Ответ:

In [21]:
last_elem = 4*10
a = np.arange(0, last_elem, 10)
b = np.arange(0,5)
print(b+a.reshape(-1,1))

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]


# task: 11

Создайте двумерный массив 8х8, заполненный 0 и 1 в шахматном порядке

In [22]:
a = np.zeros((8, 8))

In [23]:
a[0:9:2, 0:9:2] = 1

In [24]:
a[1:9:2, 1:9:2] = 1

In [25]:
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# task: 12

1. Создайте одномерный массив целых чисел от 1 до 5
2. Вставьте 0 между каждой парой соседних элементов

In [26]:
length = 5

a = np.arange(1, length+1)

In [27]:
%%timeit
np.insert(a, np.arange(1, length), 0)

13.4 µs ± 43.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
%%timeit
np.insert(a, slice(1, length), 0)

12.6 µs ± 484 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [29]:
%%timeit
b = np.zeros(length*2-1)
b[0::2] = a

1.03 µs ± 32.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Ответ:

In [30]:
length = 5
a = np.arange(1, length+1)
b = np.zeros(length*2-1)
b[0::2] = a
print(b)

[1. 0. 2. 0. 3. 0. 4. 0. 5.]


# task: 13

"Что будет выведено на экран?
x = np.arange(36).reshape(2,3,2,3)
print(x[...,0,...])"
ellipsis

14
"""
"Что будет выведено на экран?
x = np.arange(16).reshape(4,4)
y = x[:,[2,3]]
y[:] = 0
print(x)
y = x[:,:2]
y[:] = 0
print(x)"
"""

# task: 15

Замените отрицательные элементы массива нулем.

In [31]:
a = np.random.rand(3,4) - 0.5

In [32]:
a

array([[ 0.19408258,  0.39264662,  0.4839955 , -0.43483731],
       [ 0.44732283,  0.34930903,  0.44184189,  0.48443588],
       [-0.08629973,  0.47844308,  0.43151476,  0.09697738]])

In [33]:
a[a < 0] = 0

In [34]:
a

array([[0.19408258, 0.39264662, 0.4839955 , 0.        ],
       [0.44732283, 0.34930903, 0.44184189, 0.48443588],
       [0.        , 0.47844308, 0.43151476, 0.09697738]])

# task: 16

На примере целочисленного массива ```x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int)``` составьте новый массив, не содержащий строки, полностью заполненные одним уникальным значением.

In [35]:
x = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 1], [2, 2, 2]], dtype=int)

In [36]:
x[np.max(x, axis = 1) > np.min(x, axis = 1)]

array([[1, 2, 3],
       [2, 2, 1]])

# task: 17

Для заданного одномерного массива x выведите все элементы, не превышающие своих соседей (первый и последний элемент сравниваются только со вторым и предпоследним соответственно).

In [37]:
x = np.random.randint(0, 10, 10)

In [38]:
x

array([8, 1, 7, 3, 0, 3, 8, 4, 1, 0])

In [39]:
x[np.r_[x[:-1]<=x[1:], True] & np.r_[True, x[1:]<=x[:-1]]]

array([1, 0, 0])

# task: 18

1. Создайте двумерный массив 3x3, заполненный случайными числами от 0 до 9
2. Отсортируйте строки массива по возрастанию значения во втором столбце

In [40]:
a = np.random.randint(0, 10, (3, 3))

In [41]:
a

array([[1, 5, 5],
       [4, 3, 1],
       [5, 8, 4]])

In [42]:
a[np.argsort(a[:, 1])]

array([[4, 3, 1],
       [1, 5, 5],
       [5, 8, 4]])

# task 19
Поменяйте местами первую и вторую строки двумерного массива

In [43]:
shape = (100, 100)

a = np.random.randint(0, 20, shape)

In [44]:
b = a.copy()

In [45]:
%%timeit
np.vstack((a[1], a[0], a[2:]))

8.65 µs ± 108 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [46]:
%%timeit
a[[1, 0]] = a[[0, 1]]

4.87 µs ± 26.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [47]:
%%timeit
b[1::-1] = b[0:2]

1.01 µs ± 27.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Ответ:

In [48]:
shape = (100, 100)

a = np.random.randint(0, 20, shape)
print("In:\n", a)
a[1::-1] = a[0:2]
print("Out:\n", a)

In:
 [[ 5  9  0 ...  8 10  2]
 [ 6  8  5 ...  3 15 10]
 [12 19 18 ...  1 13 18]
 ...
 [14 16  6 ... 11 13  0]
 [ 5  0  7 ...  8 14  8]
 [ 3 11 14 ... 17 11 13]]
Out:
 [[ 6  8  5 ...  3 15 10]
 [ 5  9  0 ...  8 10  2]
 [12 19 18 ...  1 13 18]
 ...
 [14 16  6 ... 11 13  0]
 [ 5  0  7 ...  8 14  8]
 [ 3 11 14 ... 17 11 13]]


# task 20

1. Создайте массив 3x5, заполненный числами от 0 до 14
2. Выберите 1, 3 строки и 2, 4 столбцы, не удаляя элементы из массива

In [49]:
shape = (30, 150)
a = np.random.randint(0, 15, shape)

In [50]:
%%timeit
a[np.ix_([0, 2], [1, 3])]

10.6 µs ± 132 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [51]:
%%timeit
a[[0, 2]][:, [1, 3]]

5.08 µs ± 46.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Ответ:

In [52]:
shape = (3, 15)
a = np.random.randint(0, 15, shape)
print("In:\n", a)
print("Out:\n", a[[0, 2]][:, [1, 3]])

In:
 [[ 9  8  7  5 12  3  4  3  2  3 11  9 10  1  7]
 [ 4  1  8 13  7  1  4 13 11  2  9  5 11  3 11]
 [13  0  1 12  5  7  9  6  8 12  1  6 12 14  5]]
Out:
 [[ 9  8  7  5 12  3  4  3  2  3 11  9 10  1  7]
 [ 4  1  8 13  7  1  4 13 11  2  9  5 11  3 11]
 [13  0  1 12  5  7  9  6  8 12  1  6 12 14  5]]


# task 21
Что будет выведено на экран?

```Python
x = np.arange(5)
x[[0,0,1]] = range(3)
print(x)
x[[1,2,1]] += 1
print(x)
```

**My ans:**
```
[1, 2, 2, 3, 4]
[1, 3, 3, 3, 4]
```

In [53]:
x = np.arange(5)
x[[0, 0, 1]] = range(3)
print(x)
x[[1, 2, 1]] += 1
print(x)

[1 2 2 3 4]
[1 3 3 3 4]


# task: 22
Перечислите все известные вам способы преобразования заданного n-мерного массива в одномерный. Какой из способов работает быстрее и почему?

In [54]:
shape_param = 100

x = np.random.randint(0, 10, [shape_param]*4)

In [55]:
%%time
np.ravel(x).shape

CPU times: user 32 µs, sys: 2 µs, total: 34 µs
Wall time: 37.7 µs


(100000000,)

In [56]:
%%time
np.reshape(x, (-1,)).shape

CPU times: user 21 µs, sys: 2 µs, total: 23 µs
Wall time: 26 µs


(100000000,)

In [57]:
%%time
x.flatten().shape

CPU times: user 132 ms, sys: 144 ms, total: 276 ms
Wall time: 276 ms


(100000000,)

# task: 23
1. Создайте массив, заполненный случайными значениями
2. Замените максимальные значения массива средним

In [59]:
a = np.random.randint(0, 9, 1000)

In [61]:
b = a.copy()
c = a.copy()
d = a.copy()

In [62]:
%%timeit
np.place(a, a==np.max(a), np.mean(a))

17.4 µs ± 103 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [63]:
%%timeit
b[b == np.max(b)] = np.mean(b)

15.3 µs ± 57.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [64]:
%%timeit
np.put(c, np.max(c), np.mean(c))

16.2 µs ± 415 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [65]:
# argmax

In [66]:
%%timeit
d[np.argmax(d)] = np.mean(d)

10.8 µs ± 341 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# task: 24
1. Создайте двумерный массив 6x6, заполненный случайными значениями
2. Сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом

In [68]:
a = np.random.randint(0, 10, (6, 6))

In [69]:
a

array([[4, 0, 1, 3, 6, 5],
       [4, 7, 0, 6, 1, 7],
       [1, 3, 4, 2, 7, 7],
       [1, 6, 3, 5, 7, 5],
       [1, 2, 1, 7, 9, 0],
       [6, 6, 0, 3, 2, 1]])

In [70]:
np.min(a, axis=0)

array([1, 0, 0, 2, 1, 0])

In [71]:
np.sum(a, axis=1)/np.min(a, axis=0)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([19. ,  inf,  inf, 13.5, 20. ,  inf])

# task: 25

1. Создайте одномерный массив длины 10, заполненный случайными значениями
2. Линейно отобразите элементы массива в отрезок [0, 1], при этом минимальный элемент должен отобразиться в 0, а максимальный - в 1

In [72]:
x = np.random.randint(0, 9, (10,))

In [73]:
x

array([4, 4, 7, 8, 6, 4, 0, 4, 1, 7])

In [74]:
(x-np.min(x))/np.ptp(x)

array([0.5  , 0.5  , 0.875, 1.   , 0.75 , 0.5  , 0.   , 0.5  , 0.125,
       0.875])

# task: 26
Замените все вхождения nan в двумерный массив средним значением по соответствующему столбцу

In [75]:
x = np.random.random((3, 5))

In [76]:
x[0, :] = np.nan

In [77]:
x

array([[       nan,        nan,        nan,        nan,        nan],
       [0.59168013, 0.27947362, 0.07883209, 0.78717723, 0.3656654 ],
       [0.08596805, 0.07608995, 0.16923771, 0.75945595, 0.7107782 ]])

In [78]:
x[np.isnan(x)] = np.nanmean(x, axis=0)

In [79]:
x

array([[0.33882409, 0.17778179, 0.1240349 , 0.77331659, 0.5382218 ],
       [0.59168013, 0.27947362, 0.07883209, 0.78717723, 0.3656654 ],
       [0.08596805, 0.07608995, 0.16923771, 0.75945595, 0.7107782 ]])

In [80]:
x.fill(np.nan)

In [81]:
#x[np.isnan(x)] = np.nanmean(x, axis=0)

In [82]:
np.nan_to_num(x, nan = np.nanmean(x, axis=0))

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: Mean of empty slice
  """Entry point for launching an IPython kernel.


array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

In [83]:
x

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

# task 27: 
Проверьте, есть ли в двумерном массиве столбец, полностью заполненый нулями.

In [84]:
x = np.random.randint(-100, 100, (1000, 1000))

In [85]:
x

array([[ 17, -64,  79, ...,   6,  97, -41],
       [ -8,  42,  65, ..., -48, -18,  42],
       [ 60,  84,  87, ..., -43,  87, -47],
       ...,
       [  0,  28,  10, ...,  33, -89, -89],
       [-75,  20, -62, ...,  52, -51, -53],
       [ 84,  43,  74, ...,  27,  -2,  74]])

In [86]:
%%timeit
np.any(np.count_nonzero(x, axis = 1) == 0)

1.24 ms ± 32.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [87]:
%%timeit
np.any(np.all(x == 0, axis = 0))

405 µs ± 346 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [88]:
%%timeit
np.any(np.prod(x + 1, axis = 0) == 1)

1.02 ms ± 12.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# task 28:
1. Создайте массив случайных чисел от 0 до 9 размером 3x4x3x4
2. Вычислите суммы элементов по двум последним осям

In [89]:
a = np.random.randint(0, 10, (3, 4, 3, 4))

In [90]:
np.sum(a, axis=(2, 3))

array([[71, 68, 44, 40],
       [50, 65, 73, 61],
       [57, 59, 44, 63]])

# task 29:

1. Любым способом создайте два массива одинаковой длины
2. Создайте массив, в котором на четных позициях будут стоять элементы с соответствующих позиций первого массива, а на нечетных - с соответствующих позиций второго

In [91]:
length = 10
a = np.ones(length)
b = np.ones(length) + 1

In [92]:
c = np.zeros(length * 2)
c[0::2] = a
c[1::2] = b

# task 30:

На примере массива ```x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])``` вычислите долю пропущенных значений

In [93]:
x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])

In [94]:
x.size

8

In [95]:
np.sum(np.isnan(x))/np.prod(x.shape)

0.375

# task 31:
На примере массива ```x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])``` составьте массив из уникальных значений массива без учета nan

In [96]:
scale = 100

x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]]*scale)

In [97]:
%%timeit
uni = np.unique(x)
uni[~ np.isnan(uni)]

13.6 µs ± 257 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [98]:
%%timeit
nonan = x[~ np.isnan(x)]
nonan = np.unique(nonan)

13.7 µs ± 765 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# task 32:

На примере массива ```x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])``` найдите максимальный элемент в массиве среди элементов, перед которыми стоит нулевой

In [99]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

In [100]:
np.max(x[np.r_[False, x == 0][:-1]])

5

# task 33:
Пусть заданы два массива одинакового размера. Поэлементно разделите один массив на другой. В случае, если делитель равен нулю, соответствующему элементу результирующего массива присвойте нуль.

In [101]:
length = 1000
a = np.random.randint(1, 10, length)
b = np.random.randint(0, 3, length)

In [102]:
%%timeit
c = np.divide(a, b, where=(b!=0))
c[b == 0] = 0

9.96 µs ± 240 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [103]:
%%timeit
c = np.divide(a, b)
c[b == 0] = 0

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


6.76 µs ± 12.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [104]:
%%timeit
c = np.where(b == 0, 0, a / b)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


7.09 µs ± 32.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# task 34:

Пусть заданы два массива ```x = np.ones(10)``` и ```i = np.array([0, 1, 2, 3, 5, 5, 5, 8])```. Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [105]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])

In [106]:
pos, counts = np.unique(i, return_counts=True)

In [107]:
x[pos] += counts

In [108]:
x

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

# task 35:

По заданному массиву ```y = np.bincount([0, 0, 3, 8, 10, 10, 11])``` постройте массив x такой, чтобы ```np.bincount(x) = y```

In [109]:
y = np.bincount([0, 0, 3, 8, 10, 10, 11])

In [110]:
x = np.repeat(np.arange(0, y.shape[0]), y)

In [111]:
np.all(np.bincount(x) == y)

True

# task 36:

Определите самые часто встречающиеся элементы в массиве целых неотрицательных чисел.
Решите задачу на примере массива ```x = np.array([0,1,2,0,6,6,7,4,5,4])```.

In [112]:
x = np.array([0,1,2,0,6,6,7,4,5,4])

In [113]:
val, freq = np.unique(x, return_counts=True)

In [114]:
val[freq==np.max(freq)]

array([0, 4, 6])

# task 37:

Разбейте двумерный массив на список двумерных массивов по уникальным значениям в первом столбце.
Решите задачу на примере массива ```x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5]])```, в результате должен получиться список ```[array([[1, 2], [1, 3]]), array([[2, 2]]), array([[3, 4], [3, 5]])]```.

In [115]:
x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5]])

In [116]:
x

array([[1, 2],
       [1, 3],
       [2, 2],
       [3, 4],
       [3, 5]])

In [117]:
[np.array([[1, 2], [1, 3]]), np.array([[2, 2]]), np.array([[3, 4], [3, 5]])]

[array([[1, 2],
        [1, 3]]),
 array([[2, 2]]),
 array([[3, 4],
        [3, 5]])]

In [118]:
_, freq = np.unique(x[:, :1], return_counts=True)

In [119]:
np.array_split(x, np.cumsum(freq)[:-1], axis=0)

[array([[1, 2],
        [1, 3]]),
 array([[2, 2]]),
 array([[3, 4],
        [3, 5]])]

# task 38:

По заданному одномерному массиву неотрицательных чисел постройте список подмассивов, сожержащих элементы из полуинтервалов ```[i * 10, (i+1) * 10), i = 0, 1, 2, …```
Решите задачу на примере массива ```x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20])```, в результате должен получиться список ```[array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])]```.

In [120]:
x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20])

In [121]:
[np.array([0, 2, 2, 8]), np.array([10, 11, 13, 18]), np.array([20, 24]), np.array([34])]

[array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])]

In [122]:
np.array_split(np.sort(x), np.cumsum(np.histogram(x, bins = np.arange(0, np.max(x), 10))[0]))

[array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])]

# task 39:

Перечислите все известные вам способы соединения заданных двумерных массивов по вертикали. Какой из способов работает быстрее?

In [123]:
shape = (10000, 10000)
a = np.random.randint(1, 5, shape)
b = np.random.randint(5, 10, shape)

In [124]:
%%time
x = np.vstack((a,b))

CPU times: user 287 ms, sys: 260 ms, total: 548 ms
Wall time: 546 ms


In [125]:
print(x.shape)

(20000, 10000)


In [126]:
%%time
x = np.concatenate((a,b))

CPU times: user 267 ms, sys: 284 ms, total: 551 ms
Wall time: 551 ms


In [127]:
print(x.shape)

(20000, 10000)


### Ответ:

In [128]:
x = np.concatenate((a,b))

# task 40:

Для двух одномерных массивов ```x = np.arange(3)``` и ```y = np.arange(5)``` постройте двумерный массив строки которого - всевозможные пары элементов из x и y.

In [129]:
x = np.arange(3)
y = np.arange(5)

# !

# task 41:

По двум входным одномерным массивам одинаковой длины составьте массив пар элементов с одинаковыми индесами.
Решите задачу на примере массивов ```x = np.array([1,2,3,4])``` и ```y = np.array([5,6,7,8])```.

In [130]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [131]:
np.stack((x, y), axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# task 42:
По заданному непустому списку двумерных массивов одинаковых размеров составьте трехмерный массив в котором вдоль нулевой оси расположены массивы из списка, между каждой парой которых вставлен массив полностью заполненный нулями.
Решите задачу для списка ```l = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]), np.array([[9, 10], [11, 12]])]```.

In [132]:
l = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]), np.array([[9, 10], [11, 12]])]

In [133]:
l

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

# !

# task 43:
Преобразуйте одномерный массив ```x = np.array([3,7,2,5,0,9,8,2,4,5])``` в двумерный массив, первая строка которого - элементы массива x с индексами от 0 до 4, вторая строка - с 1 до 5 и т.д.

In [134]:
x = np.array([3,7,2,5,0,9,8,2,4,5])

In [135]:
x.reshape(-1, 5)

array([[3, 7, 2, 5, 0],
       [9, 8, 2, 4, 5]])

# task 44:
Для заданного двумерного массива постройте трехмерный массив, содержащий всевозможные неперекрывающиеся блоки размера 3x3, начиная с левого верхнего угла. Если высота/ширина исходного массива не кратна трем, исключите из рассмотрения последние строки/столбцы.
Решите задачу на примере массива ```x = np.arange(49).reshape(7,7)```.

In [136]:
x = np.arange(49).reshape(7,7)

In [137]:
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [138]:
x = x[:(x.shape[0]//3)*3, :(x.shape[1]//3)*3]

In [139]:
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11, 12],
       [14, 15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25, 26],
       [28, 29, 30, 31, 32, 33],
       [35, 36, 37, 38, 39, 40]])

# !

# task 45:
Примените маску к элементам одномерного массива, отличающимся от среднего на величину, большую чем 3 стандартных отклонения.
Решите задачу на примере массива из 20 элеметнов, первый из которых равен 100, а остальные равны 0.

In [140]:
length = 1000
a = np.zeros(length)
a[0] = 5*length

In [141]:
mean, std = np.mean(a), np.std(a)
print(mean, std)

5.0 158.03480629279107


In [142]:
%%time
a[np.abs(a-mean) > 3*std]

CPU times: user 143 µs, sys: 5 µs, total: 148 µs
Wall time: 120 µs


array([5000.])

In [143]:
%%time
a[(a > mean + 3 * std) | (a < mean - 3 * std)]

CPU times: user 142 µs, sys: 5 µs, total: 147 µs
Wall time: 114 µs


array([5000.])

### Ответ:

In [144]:
length = 20
a = np.zeros(length)
a[0] = 5*length
mean, std = np.mean(a), np.std(a)
a[np.abs(a-mean) > 3*std]

array([100.])

# task 46:
Удалите из двумерного массива столбцы, ко всем элементам которых применена маска.
Решите задачу на примере массива ```x = np.ma.array([[1, 2, 3], [4, 5, 6]], mask=[[1, 1, 0], [0, 1, 0]])```.

In [145]:
x = np.ma.array([[1, 2, 3], [4, 5, 6]], mask=[[1, 1, 0], [0, 1, 0]])

In [146]:
x

masked_array(
  data=[[--, --, 3],
        [4, --, 6]],
  mask=[[ True,  True, False],
        [False,  True, False]],
  fill_value=999999)

In [147]:
np.delete(x.data, np.prod(x.mask, axis=0).astype(bool), axis=1)

array([[1, 3],
       [4, 6]])

# task 47:
Примените маску к минимальному и максимальному элементу каждой строки двумерного массива.
Решите задачу на примере массива ```x = np.arange(25).reshape(5, 5)```.

In [148]:
x = np.arange(25).reshape(5, 5)

In [149]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# !

# task 48:

Примените медианный фильтр с нечетной шириной окна k к заданному одномерному массиву a: i-е значение результирующего массива вычисляется как медиана подмассива ```a[i - (k-1)/2: i - (k-1)/2 + 1]```. В случае если границы окна выходят за границы массива, дополните исходный массив требуемым числом элементов a[0] или a[-1] с нужной стороны.
Решите задачу на примере массива ```a = np.array([3, 8, 100, -3, -7, 4, 0, 2])``` и ширины окна k = 5.

# !

# task 49:

По заданному массиву a размера Nx2 постройте одномерный массив длины N, i-й элемент которого - сумма i-го элемента первого столбца массива a и элемента первого столбца, индекс которого содержится в i-й строке второго столбца. В случае, если во втором столбце массива a содержится индекс, выходящий за границы, к элементу первого столбца ничего не прибавляйте.
Решите задачу на примере массива ```a = np.array([[10, 1], [3, 1], [8, 2], [6, 1], [12, 5]])```.

In [150]:
a = np.array([[10, 1], [3, 1], [8, 2], [6, 1], [12, 5]])

In [151]:
a

array([[10,  1],
       [ 3,  1],
       [ 8,  2],
       [ 6,  1],
       [12,  5]])

# task 50:

По заданному двумерному массиву размера NxN постройте словарь, ключи которого - индексы диагоналей, параллельных побочной (нумерация начинается с 0), а значения - списки элементов исходного массива, лежащих на соответствующих диагоналях.
Решите задачу на примере массива ```a = np.arange(16).reshape(4, 4)```, в результате должен получиться словарь
```
{0: [0],
 1: [1, 4],
 2: [2, 5, 8],
 3: [3, 6, 9, 12],
 4: [7, 10, 13],
 5: [11, 14],
 6: [15]}.
```