In [1]:
import numpy as np

# task: 1

1. Создайте массив длины 10, заполненный нулями
2. Сделайте полученный массив неизменяемым

In [2]:
arr = np.zeros(10)

In [3]:
arr.setflags(write=False)

In [4]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

# task: 2

1. Создайте массив, содержащий 5 равноотстоящих точек, покрывающих диапазон от 0 до 2*pi
2. Создайте массив, содержащий 5 равноотстоящих в логарифмическом масштабе точек, покрывающих диапазон от 10 до 100
3. Составьте из полученных массивов координатную сеть (meshgrid)

In [5]:
arr_x = np.linspace(0, 2*np.pi, 5)

In [6]:
arr_y = np.logspace(10, 100, 5)

In [7]:
np.meshgrid(arr_x, arr_y)

[array([[0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531],
        [0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531]]),
 array([[1.00000000e+010, 1.00000000e+010, 1.00000000e+010,
         1.00000000e+010, 1.00000000e+010],
        [3.16227766e+032, 3.16227766e+032, 3.16227766e+032,
         3.16227766e+032, 3.16227766e+032],
        [1.00000000e+055, 1.00000000e+055, 1.00000000e+055,
         1.00000000e+055, 1.00000000e+055],
        [3.16227766e+077, 3.16227766e+077, 3.16227766e+077,
         3.16227766e+077, 3.16227766e+077],
        [1.00000000e+100, 1.00000000e+100, 1.00000000e+100,
         1.00000000e+100, 1.00000000e+100]])]

# task: 3

Создайте двумерный массив 5х5 с элементами 1, 2, 3 и 4 под главной диагональю, остальные элементы заполните нулями

In [8]:
size = 100

In [9]:
%%timeit
arr1 = np.diag(range(1, size), -1)

17.9 µs ± 219 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
%%timeit
arr2 = np.zeros((size, size))
arr2[range(1,size), range(0,size-1)] = range(1,size)

40.2 µs ± 102 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### Ответ:

In [11]:
np.diag(range(1, 5), -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# task: 4 

1. Создайте функцию-генератор, последовательно возвращающую целые числа от 0 до 9
2. Создайте массив из построенного генератора

In [12]:
def gen_num(min_num, max_num):
    num = min_num
    while num <= max_num:
        yield num
        num += 1   

In [13]:
stop_num = 10000

In [14]:
%%timeit
gen = gen_num(0, stop_num)
np.fromiter(gen, int)

851 µs ± 25.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [15]:
def gen_num_range(min_num, max_num):
    for num in range(min_num, max_num+1):
        yield num

In [16]:
%%timeit
gen = gen_num_range(0, stop_num)
np.fromiter(gen, int)

589 µs ± 18.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Ответ

In [17]:
def gen_num_range(min_num, max_num):
    for num in range(min_num, max_num+1):
        yield num
        
gen = gen_num_range(0, 9)
np.fromiter(gen, int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# task: 9

1. Создайте масив из четырех элементов: 0, 10, 20, 30
2. Создайте двухмерный массив 4x5, в котором первый столбец - массив с шага 1, а каждый элемент каждой строки, начиная со второго,  больше предыдущего элемента этой же строки на 1.

In [18]:
last_elem = 4*1000

a = np.arange(0, last_elem, 10)
b = np.arange(0,5)

In [19]:
%%timeit
b+a[:, np.newaxis]

5.22 µs ± 187 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
%%timeit
b+a.reshape(-1,1)

5.02 µs ± 9.78 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Ответ:

In [21]:
last_elem = 4*10
a = np.arange(0, last_elem, 10)
b = np.arange(0,5)
print(b+a.reshape(-1,1))

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]


# task: 11

Создайте двумерный массив 8х8, заполненный 0 и 1 в шахматном порядке

In [22]:
a = np.zeros((8, 8))

In [23]:
a[0:9:2, 0:9:2] = 1

In [24]:
a[1:9:2, 1:9:2] = 1

In [25]:
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# task: 12

1. Создайте одномерный массив целых чисел от 1 до 5
2. Вставьте 0 между каждой парой соседних элементов

In [26]:
length = 5

a = np.arange(1, length+1)

In [27]:
%%timeit
np.insert(a, np.arange(1, length), 0)

12.7 µs ± 40.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
%%timeit
np.insert(a, slice(1, length), 0)

12.5 µs ± 53.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [29]:
%%timeit
b = np.zeros(length*2-1)
b[0::2] = a

986 ns ± 11 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Ответ:

In [30]:
length = 5
a = np.arange(1, length+1)
b = np.zeros(length*2-1)
b[0::2] = a
print(b)

[1. 0. 2. 0. 3. 0. 4. 0. 5.]


# task: 13

"Что будет выведено на экран?
```
x = np.arange(36).reshape(2,3,2,3)
print(x[...,0,...])"
ellipsis
```

14
"""
"Что будет выведено на экран?
x = np.arange(16).reshape(4,4)
y = x[:,[2,3]]
y[:] = 0
print(x)
y = x[:,:2]
y[:] = 0
print(x)"
"""

# task: 15

Замените отрицательные элементы массива нулем.

In [31]:
a = np.random.rand(3, 4) - 0.5

In [32]:
a

array([[-0.18615335, -0.24248197, -0.18481663, -0.12594967],
       [ 0.29080734,  0.37605767, -0.16107647, -0.05902807],
       [-0.37095364, -0.2517239 , -0.27511658, -0.44873419]])

In [33]:
a[a < 0] = 0

In [34]:
a

array([[0.        , 0.        , 0.        , 0.        ],
       [0.29080734, 0.37605767, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

# task: 16

На примере целочисленного массива ```x = np.array([[1,2,3], [1,1,1], [2,2,1], [2,2,2]], dtype=int)``` составьте новый массив, не содержащий строки, полностью заполненные одним уникальным значением.

In [35]:
x = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 1], [2, 2, 2]], dtype=int)

In [36]:
x[np.max(x, axis = 1) > np.min(x, axis = 1)]

array([[1, 2, 3],
       [2, 2, 1]])

# task: 17

Для заданного одномерного массива x выведите все элементы, не превышающие своих соседей (первый и последний элемент сравниваются только со вторым и предпоследним соответственно).

In [37]:
x = np.random.randint(0, 10, 10)

In [38]:
x

array([1, 1, 9, 6, 4, 1, 2, 3, 2, 9])

In [39]:
x[np.r_[x[:-1]<=x[1:], True] & np.r_[True, x[1:]<=x[:-1]]]

array([1, 1, 1, 2])

# task: 18

1. Создайте двумерный массив 3x3, заполненный случайными числами от 0 до 9
2. Отсортируйте строки массива по возрастанию значения во втором столбце

In [40]:
a = np.random.randint(0, 10, (3, 3))

In [41]:
a

array([[5, 5, 9],
       [1, 0, 5],
       [1, 4, 4]])

In [42]:
a[np.argsort(a[:, 1])]

array([[1, 0, 5],
       [1, 4, 4],
       [5, 5, 9]])

# task 19
Поменяйте местами первую и вторую строки двумерного массива

In [43]:
shape = (100, 100)

a = np.random.randint(0, 20, shape)

In [44]:
b = a.copy()

In [45]:
%%timeit
np.vstack((a[1], a[0], a[2:]))

7.88 µs ± 200 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [46]:
%%timeit
a[[1, 0]] = a[[0, 1]]

4.24 µs ± 17.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [47]:
%%timeit
b[1::-1] = b[0:2]

959 ns ± 30.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Ответ:

In [48]:
shape = (3, 4)

a = np.random.randint(0, 20, shape)
print("In:\n", a)
a[1::-1] = a[0:2]
print("Out:\n", a)

In:
 [[19 19  4  0]
 [12 16 15 13]
 [19  9  5  9]]
Out:
 [[12 16 15 13]
 [19 19  4  0]
 [19  9  5  9]]


# task 20

1. Создайте массив 3x5, заполненный числами от 0 до 14
2. Выберите 1, 3 строки и 2, 4 столбцы, не удаляя элементы из массива

In [49]:
shape = (30, 150)
a = np.random.randint(0, 15, shape)

In [50]:
%%timeit
a[np.ix_([0, 2], [1, 3])]

9.75 µs ± 402 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [51]:
%%timeit
a[[0, 2]][:, [1, 3]]

4.53 µs ± 16.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Ответ:

In [52]:
shape = (3, 5)
a = np.random.randint(0, 15, shape)
print("In:\n", a)
print("Out:\n", a[[0, 2]][:, [1, 3]])

In:
 [[14  8 13  9  4]
 [ 8  5  0  7 12]
 [12  0  4  2 11]]
Out:
 [[8 9]
 [0 2]]


# task 21
Что будет выведено на экран?

```Python
x = np.arange(5)
x[[0,0,1]] = range(3)
print(x)
x[[1,2,1]] += 1
print(x)
```

**My ans:**
```
[1, 2, 2, 3, 4]
[1, 3, 3, 3, 4]
```

In [53]:
x = np.arange(5)
x[[0, 0, 1]] = range(3)
print(x)
x[[1, 2, 1]] += 1
print(x)

[1 2 2 3 4]
[1 3 3 3 4]


# task: 22
Перечислите все известные вам способы преобразования заданного n-мерного массива в одномерный. Какой из способов работает быстрее и почему?

In [54]:
shape_param = 100

x = np.random.randint(0, 10, [shape_param]*4)

In [55]:
%%time
np.ravel(x).shape

CPU times: user 43 µs, sys: 3 µs, total: 46 µs
Wall time: 49.4 µs


(100000000,)

In [56]:
%%time
np.reshape(x, (-1,)).shape

CPU times: user 40 µs, sys: 0 ns, total: 40 µs
Wall time: 43.9 µs


(100000000,)

In [57]:
%%time
x.flatten().shape

CPU times: user 138 ms, sys: 140 ms, total: 278 ms
Wall time: 277 ms


(100000000,)

### Ответ:

reshape и ravel работают с view, в то время как flatten создает копию. ravel - частный случай reshape.

# task: 23
1. Создайте массив, заполненный случайными значениями
2. Замените максимальные значения массива средним

In [58]:
a = np.random.randint(0, 9, 1000)

In [59]:
b = a.copy()
c = a.copy()
d = a.copy()

In [60]:
%%timeit
np.place(a, a==np.max(a), np.mean(a))

17.7 µs ± 568 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [61]:
%%timeit
b[b == np.max(b)] = np.mean(b)

15.3 µs ± 42.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [62]:
%%timeit
np.put(c, np.max(c), np.mean(c))

14.5 µs ± 447 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [63]:
%%timeit
d[np.argmax(d)] = np.mean(d)
# возвращает только одно значение индекса, а не все

10.6 µs ± 154 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Ответ:

In [64]:
a = np.random.randint(0, 9, 10).astype(float)
print("In:\n", a)
print(f"Mean: {np.mean(a)}, Max: {np.max(a)}")
a[a == np.max(a)] = np.mean(a)
print("Out:\n", a)

In:
 [0. 0. 7. 6. 3. 0. 2. 4. 7. 1.]
Mean: 3.0, Max: 7.0
Out:
 [0. 0. 3. 6. 3. 0. 2. 4. 3. 1.]


# task: 24
1. Создайте двумерный массив 6x6, заполненный случайными значениями
2. Сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом

In [65]:
a = np.random.randint(0, 10, (6, 6))

In [66]:
a

array([[7, 1, 6, 7, 1, 0],
       [7, 4, 4, 5, 7, 4],
       [8, 3, 2, 1, 1, 1],
       [4, 9, 2, 0, 2, 2],
       [1, 2, 5, 4, 2, 4],
       [1, 6, 8, 2, 0, 6]])

In [67]:
np.min(a, axis=0)

array([1, 1, 2, 0, 0, 0])

In [68]:
np.sum(a, axis=1)/np.min(a, axis=0)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([22., 31.,  8., inf, inf, inf])

# task: 25

1. Создайте одномерный массив длины 10, заполненный случайными значениями
2. Линейно отобразите элементы массива в отрезок [0, 1], при этом минимальный элемент должен отобразиться в 0, а максимальный - в 1

In [69]:
x = np.random.randint(0, 9, (10,))

In [70]:
x

array([7, 4, 0, 7, 4, 6, 3, 8, 4, 6])

In [71]:
(x-np.min(x))/np.ptp(x)

array([0.875, 0.5  , 0.   , 0.875, 0.5  , 0.75 , 0.375, 1.   , 0.5  ,
       0.75 ])

# task: 26
Замените все вхождения nan в двумерный массив средним значением по соответствующему столбцу

In [72]:
x = np.random.random((3, 5))

In [73]:
x[0, :] = np.nan

In [74]:
x

array([[       nan,        nan,        nan,        nan,        nan],
       [0.85352756, 0.46844032, 0.06056932, 0.01689157, 0.2156872 ],
       [0.90637799, 0.54232406, 0.09232188, 0.66632111, 0.29797262]])

In [75]:
x[np.isnan(x)] = np.nanmean(x, axis=0)

In [76]:
x

array([[0.87995277, 0.50538219, 0.0764456 , 0.34160634, 0.25682991],
       [0.85352756, 0.46844032, 0.06056932, 0.01689157, 0.2156872 ],
       [0.90637799, 0.54232406, 0.09232188, 0.66632111, 0.29797262]])

In [77]:
x[:, 0] = np.nan

In [78]:
x

array([[       nan, 0.50538219, 0.0764456 , 0.34160634, 0.25682991],
       [       nan, 0.46844032, 0.06056932, 0.01689157, 0.2156872 ],
       [       nan, 0.54232406, 0.09232188, 0.66632111, 0.29797262]])

In [79]:
#x[np.isnan(x)] = np.nanmean(x, axis=0)

In [80]:
np.nan_to_num(x, nan = np.nanmean(x, axis=0))

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: Mean of empty slice
  """Entry point for launching an IPython kernel.


array([[       nan, 0.50538219, 0.0764456 , 0.34160634, 0.25682991],
       [       nan, 0.46844032, 0.06056932, 0.01689157, 0.2156872 ],
       [       nan, 0.54232406, 0.09232188, 0.66632111, 0.29797262]])

In [81]:
x

array([[       nan, 0.50538219, 0.0764456 , 0.34160634, 0.25682991],
       [       nan, 0.46844032, 0.06056932, 0.01689157, 0.2156872 ],
       [       nan, 0.54232406, 0.09232188, 0.66632111, 0.29797262]])

# task 27: 
Проверьте, есть ли в двумерном массиве столбец, полностью заполненый нулями.

In [82]:
x = np.random.randint(-100, 100, (1000, 1000))

In [83]:
x

array([[-43,  13, -84, ...,  63, -88, -70],
       [ 10,  72, -33, ...,  30,  -1, -84],
       [ 52,  74,  85, ...,  47,  25,  96],
       ...,
       [ -5, -71, -35, ..., -38,  -7, -66],
       [ 78,  45,  21, ..., -31, -27,  49],
       [ 10, -63, -96, ...,  24,   3, -79]])

In [84]:
%%timeit
np.any(np.count_nonzero(x, axis = 1) == 0)

1.28 ms ± 45 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [85]:
%%timeit
np.any(np.all(x == 0, axis = 0))

404 µs ± 578 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [86]:
%%timeit
np.any(np.prod(x + 1, axis = 0) == 1)

1.02 ms ± 12.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Ответ:

In [87]:
x = np.random.randint(-1, 1, (3, 10))
print(x)
print(np.any(np.all(x == 0, axis = 0)))

[[ 0  0 -1  0 -1 -1  0 -1  0 -1]
 [-1  0  0 -1  0 -1 -1 -1  0  0]
 [ 0 -1  0 -1 -1 -1  0  0  0  0]]
True


# task 28:
1. Создайте массив случайных чисел от 0 до 9 размером 3x4x3x4
2. Вычислите суммы элементов по двум последним осям

In [88]:
a = np.random.randint(0, 10, (3, 4, 3, 4))

In [89]:
np.sum(a, axis=(2, 3))

array([[58, 62, 41, 38],
       [55, 73, 58, 42],
       [46, 58, 74, 52]])

# task 29:

1. Любым способом создайте два массива одинаковой длины
2. Создайте массив, в котором на четных позициях будут стоять элементы с соответствующих позиций первого массива, а на нечетных - с соответствующих позиций второго

In [90]:
length = 10
a = np.ones(length)
b = np.ones(length) + 1
print(a, "\n", b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [91]:
c = np.zeros(length * 2)
c[0::2] = a
c[1::2] = b
print(c)

[1. 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 2. 1. 2.]


# task 30:

На примере массива ```x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])``` вычислите долю пропущенных значений

In [92]:
x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])

In [93]:
np.sum(np.isnan(x))/x.size

0.375

# task 31:
На примере массива ```x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])``` составьте массив из уникальных значений массива без учета nan

In [94]:
scale = 100

x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]]*scale)

In [95]:
%%timeit
uni = np.unique(x)
uni[~ np.isnan(uni)]

13.6 µs ± 167 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [96]:
%%timeit
nonan = x[~ np.isnan(x)]
nonan = np.unique(nonan)

12.4 µs ± 43.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Ответ:

In [97]:
x = np.array([[1., 2.], [np.nan, 3.], [5., 5.], [np.nan, np.nan]])
print("In:\n", x)
uni = np.unique(x)
uni = uni[~np.isnan(uni)]
print("Out:\n", uni)

In:
 [[ 1.  2.]
 [nan  3.]
 [ 5.  5.]
 [nan nan]]
Out:
 [1. 2. 3. 5.]


# task 32:

На примере массива ```x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])``` найдите максимальный элемент в массиве среди элементов, перед которыми стоит нулевой

In [98]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

In [99]:
np.max(x[np.r_[False, x == 0][:-1]])

5

# task 33:
Пусть заданы два массива одинакового размера. Поэлементно разделите один массив на другой. В случае, если делитель равен нулю, соответствующему элементу результирующего массива присвойте нуль.

In [100]:
length = 1000
a = np.random.randint(1, 10, length)
b = np.random.randint(0, 3, length)

In [101]:
%%timeit
c = np.divide(a, b, where=(b!=0))
c[b == 0] = 0

9.78 µs ± 28.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [102]:
%%timeit
c = np.divide(a, b)
c[b == 0] = 0

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


6.74 µs ± 8.04 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [103]:
%%timeit
c = np.where(b == 0, 0, a / b)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


7.18 µs ± 16.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Ответ:

In [104]:
length = 10
a = np.random.randint(1, 10, length)
b = np.random.randint(0, 3, length)
c = np.divide(a, b)
c[b == 0] = 0
print("In:\n", a, "\n", b)
print("Out:", c)

In:
 [6 3 6 9 9 2 2 5 8 3] 
 [2 1 0 2 2 2 0 1 2 1]
Out: [3.  3.  0.  4.5 4.5 1.  0.  5.  4.  3. ]


/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


# task 34:

Пусть заданы два массива ```x = np.ones(10)``` и ```i = np.array([0, 1, 2, 3, 5, 5, 5, 8])```. Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [105]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])

In [106]:
pos, counts = np.unique(i, return_counts=True)

In [107]:
x[pos] += counts

In [108]:
x

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

# task 35:

По заданному массиву ```y = np.bincount([0, 0, 3, 8, 10, 10, 11])``` постройте массив x такой, чтобы ```np.bincount(x) = y```

In [109]:
y = np.bincount([0, 0, 3, 8, 10, 10, 11])

In [110]:
x = np.repeat(np.arange(0, y.shape[0]), y)

In [111]:
np.all(np.bincount(x) == y)

True

# task 36:

Определите самые часто встречающиеся элементы в массиве целых неотрицательных чисел.
Решите задачу на примере массива ```x = np.array([0,1,2,0,6,6,7,4,5,4])```.

In [112]:
x = np.array([0,1,2,0,6,6,7,4,5,4])

In [113]:
val, freq = np.unique(x, return_counts=True)

In [114]:
val[freq==np.max(freq)]

array([0, 4, 6])

# task 37:

Разбейте двумерный массив на список двумерных массивов по уникальным значениям в первом столбце.
Решите задачу на примере массива ```x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5]])```, в результате должен получиться список ```[array([[1, 2], [1, 3]]), array([[2, 2]]), array([[3, 4], [3, 5]])]```.

In [115]:
x = np.array([[1, 2], [1, 3], [2, 2], [3, 4], [3, 5]])

In [116]:
x

array([[1, 2],
       [1, 3],
       [2, 2],
       [3, 4],
       [3, 5]])

In [117]:
[np.array([[1, 2], [1, 3]]), np.array([[2, 2]]), np.array([[3, 4], [3, 5]])]

[array([[1, 2],
        [1, 3]]),
 array([[2, 2]]),
 array([[3, 4],
        [3, 5]])]

In [118]:
_, freq = np.unique(x[:, :1], return_counts=True)

In [119]:
np.array_split(x, np.cumsum(freq)[:-1], axis=0)

[array([[1, 2],
        [1, 3]]),
 array([[2, 2]]),
 array([[3, 4],
        [3, 5]])]

# task 38:

По заданному одномерному массиву неотрицательных чисел постройте список подмассивов, сожержащих элементы из полуинтервалов ```[i * 10, (i+1) * 10), i = 0, 1, 2, …```
Решите задачу на примере массива ```x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20])```, в результате должен получиться список ```[array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])]```.

In [120]:
x = np.array([8, 2, 34, 0, 11, 18, 13, 2, 24, 10, 20])

In [121]:
[np.array([0, 2, 2, 8]), np.array([10, 11, 13, 18]), np.array([20, 24]), np.array([34])]

[array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])]

In [122]:
np.array_split(np.sort(x), np.cumsum(np.histogram(x, bins = np.arange(0, np.max(x), 10))[0]))

[array([0, 2, 2, 8]), array([10, 11, 13, 18]), array([20, 24]), array([34])]

# task 39:

Перечислите все известные вам способы соединения заданных двумерных массивов по вертикали. Какой из способов работает быстрее?

## Тест на данных большого размера

In [123]:
shape = (10000, 10000)
a = np.random.randint(1, 5, shape)
b = np.random.randint(5, 10, shape)

### Способ 1:

In [124]:
%%time
x = np.vstack((a,b))

CPU times: user 480 ms, sys: 480 ms, total: 960 ms
Wall time: 959 ms


In [125]:
print(x.shape)

(20000, 10000)


### Способ 2:

In [126]:
%%time
x = np.concatenate((a,b))

CPU times: user 490 ms, sys: 504 ms, total: 994 ms
Wall time: 994 ms


In [127]:
print(x.shape)

(20000, 10000)


### Способ 3:

In [128]:
%%time
x = np.r_[a, b]

CPU times: user 498 ms, sys: 496 ms, total: 994 ms
Wall time: 994 ms


In [129]:
print(x.shape)

(20000, 10000)


### Способ 4:

In [130]:
%%time
x = np.row_stack((a, b))

CPU times: user 523 ms, sys: 480 ms, total: 1 s
Wall time: 1 s


In [131]:
print(x.shape)

(20000, 10000)


## Тест на данных малого размера

In [132]:
shape = (3, 10)
a = np.random.randint(1, 5, shape)
b = np.random.randint(5, 10, shape)

### Способ 1:

In [133]:
%%timeit
x = np.vstack((a,b))

4.1 µs ± 115 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [134]:
print(x.shape)

(20000, 10000)


### Способ 2:

In [135]:
%%timeit
x = np.concatenate((a,b))

1.19 µs ± 19.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [136]:
print(x.shape)

(20000, 10000)


### Способ 3:

In [137]:
%%timeit
x = np.r_[a, b]

11.9 µs ± 277 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [138]:
print(x.shape)

(20000, 10000)


### Способ 4:

In [139]:
%%timeit
x = np.row_stack((a, b))

3.97 µs ± 10.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [140]:
print(x.shape)

(20000, 10000)


### Отличия способов
 * concatenate имеет более широкий функционал, чем vstack.
 * vstack эквивалентен concatenation по первой оси после того, как 1-D массивы формы (N,) были приведены к форме (1,N).
 * np.r_ конкатенация по первой оси
 * row_stack = vstack

### Ответ:

In [141]:
shape = (2, 10)
a = np.random.randint(1, 5, shape)
b = np.random.randint(5, 10, shape)
x = np.concatenate((a,b))
print("In:\n", a, "\nand:\n", b)
print("Out:\n", x)

In:
 [[1 2 3 2 4 4 1 1 1 1]
 [2 2 1 4 3 1 4 2 1 1]] 
and:
 [[9 9 6 6 8 6 9 9 6 6]
 [5 7 8 8 7 8 8 7 6 5]]
Out:
 [[1 2 3 2 4 4 1 1 1 1]
 [2 2 1 4 3 1 4 2 1 1]
 [9 9 6 6 8 6 9 9 6 6]
 [5 7 8 8 7 8 8 7 6 5]]


# task 40:

Для двух одномерных массивов ```x = np.arange(3)``` и ```y = np.arange(5)``` постройте двумерный массив строки которого - всевозможные пары элементов из x и y.

In [142]:
x = np.arange(3)
y = np.arange(5)

In [143]:
a, b = np.meshgrid(x, y)

In [144]:
np.reshape(np.stack((a, b), axis=-1), (-1, 2))

array([[0, 0],
       [1, 0],
       [2, 0],
       [0, 1],
       [1, 1],
       [2, 1],
       [0, 2],
       [1, 2],
       [2, 2],
       [0, 3],
       [1, 3],
       [2, 3],
       [0, 4],
       [1, 4],
       [2, 4]])

**Отличия np.reshape(x, ...) и x.reshape(...): только синтаксис, внутри одно и то же.**

# task 41:

По двум входным одномерным массивам одинаковой длины составьте массив пар элементов с одинаковыми индесами.
Решите задачу на примере массивов ```x = np.array([1,2,3,4])``` и ```y = np.array([5,6,7,8])```.

In [145]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [146]:
np.stack((x, y), axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# task 42:
По заданному непустому списку двумерных массивов одинаковых размеров составьте трехмерный массив в котором вдоль нулевой оси расположены массивы из списка, между каждой парой которых вставлен массив полностью заполненный нулями.
Решите задачу для списка ```l = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]), np.array([[9, 10], [11, 12]])]```.

In [147]:
l = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]), np.array([[9, 10], [11, 12]])]

In [148]:
l

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [149]:
np.insert(np.stack(l), range(1, len(l), 1), np.zeros(l[0].shape), axis=0)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 0,  0],
        [ 0,  0]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 0,  0],
        [ 0,  0]],

       [[ 9, 10],
        [11, 12]]])

# task 43:
Преобразуйте одномерный массив ```x = np.array([3,7,2,5,0,9,8,2,4,5])``` в двумерный массив, первая строка которого - элементы массива x с индексами от 0 до 4, вторая строка - с 1 до 5 и т.д.

In [150]:
x = np.array([3,7,2,5,0,9,8,2,4,5])

## Способ 1:

In [151]:
x.reshape(-1, 5)

array([[3, 7, 2, 5, 0],
       [9, 8, 2, 4, 5]])

## Способ 2:

In [152]:
np.lib.stride_tricks.as_strided(x, strides=(5*x.itemsize,  1*x.itemsize), shape=(2,5))

array([[3, 7, 2, 5, 0],
       [9, 8, 2, 4, 5]])

# task 44:
Для заданного двумерного массива постройте трехмерный массив, содержащий всевозможные неперекрывающиеся блоки размера 3x3, начиная с левого верхнего угла. Если высота/ширина исходного массива не кратна трем, исключите из рассмотрения последние строки/столбцы.
Решите задачу на примере массива ```x = np.arange(49).reshape(7,7)```.

In [153]:
x = np.arange(49).reshape(7, 7)

In [154]:
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [155]:
arrays_in_row, arrays_in_col = x.shape[0] // 3, x.shape[1] // 3

np.lib.stride_tricks.as_strided(x, 
                                strides=(3*x.shape[0]*x.itemsize, 3*x.itemsize, x.shape[0]*x.itemsize, 1*x.itemsize), 
                                shape=(arrays_in_row, arrays_in_col, 3, 3)
                               ).reshape((arrays_in_col*arrays_in_row, 3, 3))

array([[[ 0,  1,  2],
        [ 7,  8,  9],
        [14, 15, 16]],

       [[ 3,  4,  5],
        [10, 11, 12],
        [17, 18, 19]],

       [[21, 22, 23],
        [28, 29, 30],
        [35, 36, 37]],

       [[24, 25, 26],
        [31, 32, 33],
        [38, 39, 40]]])

# task 45:
Примените маску к элементам одномерного массива, отличающимся от среднего на величину, большую чем 3 стандартных отклонения.
Решите задачу на примере массива из 20 элеметнов, первый из которых равен 100, а остальные равны 0.

In [156]:
length = 1000
a = np.zeros(length)
a[0] = 5*length

In [157]:
mean, std = np.mean(a), np.std(a)
print(mean, std)

5.0 158.03480629279107


In [158]:
%%time
a[np.abs(a-mean) > 3*std]

CPU times: user 107 µs, sys: 4 µs, total: 111 µs
Wall time: 82 µs


array([5000.])

In [159]:
%%time
a[(a > mean + 3 * std) | (a < mean - 3 * std)]

CPU times: user 41 µs, sys: 2 µs, total: 43 µs
Wall time: 47.7 µs


array([5000.])

### Ответ:

In [160]:
length = 20
a = np.zeros(length)
a[0] = 5*length
mean, std = np.mean(a), np.std(a)
a[np.abs(a-mean) > 3*std]

array([100.])

# task 46:
Удалите из двумерного массива столбцы, ко всем элементам которых применена маска.
Решите задачу на примере массива ```x = np.ma.array([[1, 2, 3], [4, 5, 6]], mask=[[1, 1, 0], [0, 1, 0]])```.

In [161]:
x = np.ma.array([[1, 2, 3], [4, 5, 6]], mask=[[1, 1, 0], [0, 1, 0]])

In [162]:
x

masked_array(
  data=[[--, --, 3],
        [4, --, 6]],
  mask=[[ True,  True, False],
        [False,  True, False]],
  fill_value=999999)

In [163]:
np.delete(x.data, np.all(x.mask==True, axis=0), axis=1)

array([[1, 3],
       [4, 6]])

# task 47:
Примените маску к минимальному и максимальному элементу каждой строки двумерного массива.
Решите задачу на примере массива ```x = np.arange(25).reshape(5, 5)```.

In [164]:
x = np.arange(25).reshape(5, 5)

In [165]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [166]:
#x = np.array([[0, 1, 1], [10, -10, 0]])

In [167]:
np.ma.array(x, 
            mask=(np.equal(x, np.max(x, axis=1).reshape(x.shape[0], -1)) | \
                  np.equal(x, np.min(x, axis=1).reshape(x.shape[0], -1))))

masked_array(
  data=[[--, 1, 2, 3, --],
        [--, 6, 7, 8, --],
        [--, 11, 12, 13, --],
        [--, 16, 17, 18, --],
        [--, 21, 22, 23, --]],
  mask=[[ True, False, False, False,  True],
        [ True, False, False, False,  True],
        [ True, False, False, False,  True],
        [ True, False, False, False,  True],
        [ True, False, False, False,  True]],
  fill_value=999999)

# task 48:

Примените медианный фильтр с нечетной шириной окна k к заданному одномерному массиву a: i-е значение результирующего массива вычисляется как медиана подмассива ```a[i - (k-1)/2: i - (k-1)/2 + 1]```. В случае если границы окна выходят за границы массива, дополните исходный массив требуемым числом элементов a[0] или a[-1] с нужной стороны.
Решите задачу на примере массива ```a = np.array([3, 8, 100, -3, -7, 4, 0, 2])``` и ширины окна k = 5.

In [168]:
a = np.array([3, 8, 100, -3, -7, 4, 0, 2])
res = np.empty(shape=a.shape, dtype=int)
k = 5

In [169]:
skip = (k-1)//2
a = np.pad(a, skip, mode='edge')
print(a)

[  3   3   3   8 100  -3  -7   4   0   2   2   2]


In [170]:
for i in range(0, len(a)-k+1):
    res[i] = np.median(a[i: i + k + 1])

In [171]:
res

array([3, 3, 3, 2, 1, 1, 2, 2])

# task 49:

По заданному массиву a размера Nx2 постройте одномерный массив длины N, i-й элемент которого - сумма i-го элемента первого столбца массива a и элемента первого столбца, индекс которого содержится в i-й строке второго столбца. В случае, если во втором столбце массива a содержится индекс, выходящий за границы, к элементу первого столбца ничего не прибавляйте.
Решите задачу на примере массива ```a = np.array([[10, 1], [3, 1], [8, 2], [6, 1], [12, 5]])```.

In [172]:
a = np.array([[10, 1], [3, 1], [8, 2], [6, -1], [12, 5]])

In [173]:
a

array([[10,  1],
       [ 3,  1],
       [ 8,  2],
       [ 6, -1],
       [12,  5]])

In [174]:
res = np.empty(shape=(a.shape[0],), dtype=int)
for num, (x, y) in enumerate(a):
    res[num] = x + a[y, 0] if 0 <= y < len(a) else x

In [175]:
res

array([13,  6, 16,  6, 12])

# task 50:

По заданному двумерному массиву размера NxN постройте словарь, ключи которого - индексы диагоналей, параллельных побочной (нумерация начинается с 0), а значения - списки элементов исходного массива, лежащих на соответствующих диагоналях.
Решите задачу на примере массива ```a = np.arange(16).reshape(4, 4)```, в результате должен получиться словарь
```
{0: [0],
 1: [1, 4],
 2: [2, 5, 8],
 3: [3, 6, 9, 12],
 4: [7, 10, 13],
 5: [11, 14],
 6: [15]}.
```

## Способ 1:

In [176]:
a = np.arange(16).reshape(4, 4)

In [177]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [178]:
res = {}
for iterator in range(-a.shape[1]+1, a.shape[1]):
    res[iterator+3] = list(np.diag(a[:, ::-1], -iterator))

In [179]:
res

{0: [0],
 1: [1, 4],
 2: [2, 5, 8],
 3: [3, 6, 9, 12],
 4: [7, 10, 13],
 5: [11, 14],
 6: [15]}

## Способ 2:

In [180]:
it = np.nditer(a, flags=['multi_index'])
res = {}
while not it.finished:
    if np.sum(it.multi_index) in res:
        res[np.sum(it.multi_index)].append(int(it[0]))
    else:
        res[np.sum(it.multi_index)] = [int(it[0])]   
    it.iternext()

In [181]:
res

{0: [0],
 1: [1, 4],
 2: [2, 5, 8],
 3: [3, 6, 9, 12],
 4: [7, 10, 13],
 5: [11, 14],
 6: [15]}

# Вопросы

Отличие a.mean() от np.mean()

In [182]:
?a.mean

Docstring:
a.mean(axis=None, dtype=None, out=None, keepdims=False)

Returns the average of the array elements along given axis.

Refer to `numpy.mean` for full documentation.

See Also
--------
numpy.mean : equivalent function
Type:      builtin_function_or_method


In [183]:
?np.mean

Signature: np.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)
Docstring:
Compute the arithmetic mean along the specified axis.

Returns the average of the array elements.  The average is taken over
the flattened array by default, otherwise over the specified axis.
`float64` intermediate and return values are used for integer inputs.

Parameters
----------
a : array_like
    Array containing numbers whose mean is desired. If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the means are computed. The default is to
    compute the mean of the flattened array.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, a mean is performed over multiple axes,
    instead of a single axis or all the axes as before.
dtype : data-type, optional
    Type to use in computing the mean.  For integer inputs, the default
    is `float64`; for floating point inputs, it is the same as the
    input dtype.
ou

1) There isn't systematic difference or relation. Most of the functions are written in Python which you can read. Many delegate the action to the corresponding method if it exists. The function form can also convert a list into an array before acting on it. The method call is usually a bit faster because it involves one less layer of calling.

2) There is a notable difference between numpy.sort and ndarray.sort: the former returns a copy of the array, the latter sorts in-place. 
For other methods, one can use equivalent functions just as well. The function form will accept array-like collections that can be converted to a NumPy array; this is sometimes convenient. On the other hand, this comes at the expense of a few more checks and function calls, so the method form should be a tiny bit faster.